import OverfittingLesson from './OverfittingLesson.jsx';
import { Architectures,PretrainedModels } from './AiAdvancedCourse.jsx';
import CooccurrenceExplorer from './CooccurrenceExplorer.jsx';
import { linkLearningPairs } from './aiMath.js';
import { Section,Sources,Next,Prompt } from './Common.jsx';
import { GraphExplorer,DiscreteProbability,NeuronExplorer,NetworkDiagram,TrainingExplorer } from './AiExplorers.jsx';
import { LocalPythonCommands } from './LocalPythonCommands.jsx';
import examples from './aiExampleResults.json';
import Practice from './AiPracticeLesson.jsx';

export const aiLinks=[
 ['/ai/discrete','01　離散数学の基礎'],
 ['/ai/graphs','02　グラフとマイニング'],
 ['/ai/learning','03　確率と学習の種類'],
 ['/ai/networks','04　ニューラルネットワーク'],
 ['/ai/training','05　重みを学習する'],
 ['/ai/practice','06　Pythonで実行し、結果を読む'],
 ['/ai/architectures','07　ニューラルネットワークの応用'],
 ['/ai/pretrained','08　転移学習・知識蒸留'],
];
const base=import.meta.env.BASE_URL;
const prerequisitesSource=['Google：機械学習を学ぶ前の数学','https://developers.google.com/machine-learning/crash-course/prereqs-and-prework'];
const curriculumSource=['Stanford CS229：学習内容と前提知識','https://cs229.stanford.edu/'];
const mathSource=['MIT：Mathematics for Computer Science','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/'];
const graphSource=['Stanford：Machine Learning with Graphs','https://web.stanford.edu/class/cs224w/'];
const networkSource=['PyTorch：ニューラルネットワークの構築','https://docs.pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html'];
const trainingSource=['PyTorch：モデルのパラメーターを最適化する','https://docs.pytorch.org/tutorials/beginner/basics/optimization_tutorial.html'];
function Table({head,rows}){return <div className="table-scroll"><table className="data-table design-table"><thead><tr>{head.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=>j===0?<th scope="row" key={j}>{v}</th>:<td key={j}>{v}</td>)}</tr>)}</tbody></table></div>;}
function Exercise({question,answer}){return <div className="note"><h3>確かめてみよう</h3><p>{question}</p><details><summary>考え方を確認する</summary><p>{answer}</p></details></div>;}

function Discrete(){return <>
 <p className="lede">まずは、ものを分け、数え、つながりを表すところから。そこから「データから規則を学ぶ」仕組みへ進みます。</p>
 <Section title="離散とは、一つずつ区別して扱うこと"><p>人A・B・C、成功と失敗、単語、ある／ない。こうした一つずつ区別できる対象を扱うのが<strong>離散数学</strong>です。「離散」は、ばらばらで無関係という意味ではありません。対象どうしの関係も調べます。</p><Table head={['扱うもの','例','何を考える？']} rows={[["集合","研究室の学生、読書が好きな人","誰が含まれるか"],["論理","経験あり、かつ、説明を読んだ","条件が成り立つか"],["組み合わせ","6人から共同制作者を2人選ぶ","何通りあるか"],["グラフ","共同制作した人どうしを結ぶ","どうつながるか"]]}/></Section>
 <Section title="ニューラルネットワークまで、何を順に学ぶ？"><p>機械学習の入門では、<strong>ベクトル・行列、確率・統計、関数・微分</strong>を土台に、簡単な予測モデルからニューラルネットワークへ進む構成がよく使われます。この教材では、その手前に離散数学を置き、小さなデータで順に確かめます。</p><Table head={['順番','分かるようになりたいこと','この教材では']} rows={[["集合・論理・ベクトル・行列","対象や条件を数で表す","01：0/1の表を作り、掛けて足す"],["グラフで使ってみる","関係を数え、表と図を行き来する","02：共同制作と共起ネットワーク"],["確率と教師あり・なし","何を入力にして、何を求めるか決める","03：同じ6人の、次の共同制作を考える"],["簡単な予測からニューロンへ","入力に重みを掛け、予測値を出す","04：人のルール → ロジスティック回帰 → 複数の計算部品"],["微分・勾配と学習","間違いを減らす向きへ重みを動かす","05：更新の仕組み → 成績の変化 → 過学習と検証"],["自分のPCで実験する","学習前後を比べ、結果から言える範囲を説明する","06：同じXORを100回・5000回で比較"],["基礎の先で出てくる課題を考える","正解の有無・入力の形・作りたい出力から、学び方と構造を考える","07：画像 → 文章 → ラベルなしの学習 → 生成"],["学習済みモデルを活用する","どの重みを、何をお手本にして変えるか説明する","08：転移学習 → ファインチューニング → 知識蒸留"]]}/><p>グラフマイニングは、この教材で数学を使ってみる具体例です。ニューラルネットワークの必須前提というわけではありません。また、AI全体が離散確率だけでできているわけでもありません。0/1の対象から出発し、途中で連続的な重みや微分も使います。</p><p>平均やばらつき、確率の基礎は<a href="#/statistics/basics">統計解析入門の01</a>でも確認できます。必要な数学は、使う場面で短い計算例を挟みます。</p></Section>
 <Section title="集合：誰が、何に含まれる？"><p>読書が好きな人をR＝｛A，B，C｝、工作が好きな人をW＝｛B，C，D｝とします。｛ ｝の中に、集合のメンバーを書きます。</p><Table head={['書き方','意味','この例の答え']} rows={[["R ∩ W（共通部分）","読書も工作も好き","｛B，C｝"],["R ∪ W（和集合）","読書か工作の少なくとも一方が好き","｛A，B，C，D｝"],["R ∖ W（差集合）","読書は好きだが、工作の集合には入っていない","｛A｝"]]}/><p>同じBを2回数えないので、和集合の人数は3＋3−2＝4人です。データを集計するときの重複や、共通する特徴を考える土台になります。</p></Section>
 <Section title="論理：条件を0と1で表す"><p>「当てはまらない」を0、「当てはまる」を1とします。ANDは両方、ORは少なくとも一方、<strong>XOR（排他的論理和）</strong>はどちらか一方だけが1のとき、1になります。</p><Table head={['x₁','x₂','AND','OR','XOR']} rows={[[0,0,0,0,0],[0,1,0,1,1],[1,0,0,1,1],[1,1,1,1,0]]}/><p>このように、入力の全組み合わせと答えを並べたものが<strong>真理値表</strong>です。2個の0/1なら2×2＝4通り、3個なら2×2×2＝8通りです。後で、このXORの表をニューラルネットワークに学習させます。</p></Section>
 <Section title="組み合わせと、数を並べた表"><p>6人から2人組を選ぶとき、最初の人は6通り、次の人は5通り。ただしA・BとB・Aを同じ組と数えるなら、<strong>6×5÷2＝15通り</strong>です。グラフで「どの2人がつながるか」を考えるときにも使います。</p><p>一人の特徴を［読書1，工作0，運動1］のように順番を決めて並べたものを<strong>ベクトル</strong>、全員分を行と列に並べたものを<strong>行列</strong>と呼びます。何を行に、何を列に置いたかを必ず決めます。学生番号は行の目印で、特徴の一つとして足し算する値ではありません。</p><Exercise question="0/1の質問が4個なら、回答の組み合わせは何通り？" answer="2×2×2×2＝16通りです。ただし、現実の調査で全16通りの回答者が現れるとは限りません。"/></Section>
 <Section title="同じ位置の数を掛けて、足す"><p>特徴［1，0，1］に、順番に2点・1点・3点を付けるなら、<strong>1×2＋0×1＋1×3＝5点</strong>です。このように二つのベクトルの同じ位置を掛けて足す計算を<strong>内積</strong>と呼びます。</p><Table head={['人','特徴1','特徴2','特徴3','重み［2，1，3］との内積']} rows={[["A",1,0,1,"1×2＋0×1＋1×3＝5"],["B",0,1,1,"0×2＋1×1＋1×3＝4"]]}/><p>2人分の特徴をまとめた行列をX、重みを縦に並べたベクトルをwとすると、<strong>Xw</strong>は各行でこの計算を行い、結果［5，4］を縦に並べたものです。行列の掛け算では「左の行」と「右の列」を組にして、内積を求めます。数の並び順と個数を合わせる必要があります。</p><p>04のニューロンでも、この「重みを掛けて足す」を使います。行列でまとめて書くと、何人分も同じ手順で計算できます。こうしたベクトルや行列を扱う分野が<strong>線形代数学</strong>です。</p></Section>
 <Sources links={[mathSource,prerequisitesSource,curriculumSource]}/>

 </>;}

function Graphs(){return <>
 <Section title="グラフは、点と線で関係を表す"><p>ここでの<strong>グラフ</strong>は、棒グラフのことではありません。対象を<strong>頂点（ノード）</strong>、関係を<strong>辺（エッジ）</strong>で表したものです。人の共同制作、ページ間のリンク、駅と路線などを同じ考え方で扱えます。</p><p>「関係」を何にするかで別のグラフになります。同じ授業を取ったのか、一緒に制作したのか、連絡したのか。線を引く前に定義します。フォローのように向きがある関係なら有向グラフ、制作回数も付けるなら重み付きグラフです。</p><GraphExplorer/></Section>
 <Section title="グラフマイニング：つながりから何を見つける？"><p><strong>グラフマイニング</strong>は、グラフとして表したデータから、構造や繰り返し現れるパターンを調べることです。最初は上の小さな図で、どの計算がどの問いに答えるかを確認します。</p><Table head={['問い','具体的な計算・出力','この図なら']} rows={[["直接つながる相手が多いのは？","次数を数える","CとDは3、ほかは2（C−Dあり）"],["どの集まりがつながっている？","経路や連結成分を調べる","C−Dを外すと、ABCとDEFの2つに分かれる"],["どの人たちが密につながる？","コミュニティ検出など","ABCとDEFはそれぞれ三角形。大きなデータでは手法と基準を決める"],["まだない関係の候補は？","共通の隣接頂点などを数え、リンク予測を検討する","AとDには共通するCがいる。今後つながると確定したわけではない"]]}/><p>例えば、AとDの共通の相手は、隣接頂点の集合｛B，C｝と｛C，E，F｝の共通部分｛C｝なので1人です。<strong>集合の計算が、関係を調べる計算になっています。</strong></p></Section>
 <Section title="同じ関係の計算を、Pythonで確かめる"><p>上の図で数えた「直接つながる相手の人数」を、PCにも数えさせてみます。ここはニューラルネットワークの学習ではなく、記録済みの関係を集計する練習です。</p><details><summary>関係のCSV・コード・出力を開く</summary><p>CSVの1行は共同制作した2人。sourceとtargetに名前を入れます。A−BとB−Aは同じ関係なので、一度だけ記録します。</p><div className="download-row"><a href={`${base}data/ai/collaboration-edges.csv`} download>関係のCSVを保存 ↓</a><a href={`${base}data/ai/graph.py`} download>graph.pyを保存 ↓</a></div><p>二つを同じフォルダーに保存し、その場所を開いたターミナルで次を実行します。追加のライブラリは不要です。</p><pre className="code-block"><code>python graph.py</code></pre><pre className="code-block"><code>{examples.graph.output}</code></pre><p>次数は直接つながる相手の人数です。CとDは3人、ほかは2人。AとDの共通の相手はCです。図と出力を照合し、CSVからC−Dの行を外すと何が変わるか確かめてください。</p><details><summary>確認用のコード</summary><pre className="code-block"><code>{examples.graph.code}</code></pre></details></details></Section>
 <Section title="共起ネットワーク：一緒に出る言葉を結ぶ"><p>人のつながりだけでなく、文章の中の言葉の関係も図にできます。<strong>共起ネットワーク</strong>は、決めた範囲の中で一緒に現れた語の関係を表すグラフです。「同じ感想1件」なのか「同じ文」なのかを、数える前に決めます。</p><CooccurrenceExplorer/><p>入力は文章、途中の計算は0/1の行列、出力は語どうしの関係です。図から気になる組を見つけ、原文を読んで考察するところまでが一連の作業です。</p><DownloadExample id="cooccurrence" csv="word-presence.csv" packages="numpy pandas"/><p>このPython例では、すでに0/1にしたCSVを読み、共起件数の行列と辺の一覧を出します。日本語からの自動的な語の抽出は、この計算例には含めていません。</p></Section>
 <Section title="関係の図と、計算の図をつなぐ"><p>ニューラルネットワークも、計算する場所を点、計算のつながりを矢印で描けます。ただし、共同制作のグラフの「人」と、ニューラルネットワークの「計算するニューロン」は役割が違います。</p><p>グラフを入力データとして学ぶ<strong>グラフニューラルネットワーク（GNN）</strong>もあります。グラフマイニング全体がGNNというわけではなく、次数を数えるだけなら学習は不要です。まず「関係を調べたいのか」「例から予測のルールを学びたいのか」を分けます。</p><Exercise question="C−Dを外したとき、Cの次数と、AからFへの経路はどうなる？" answer="Cの次数は3から2になります。A側とF側をつなぐ辺がなくなるので、AからFへたどる経路はなくなります。"/></Section>
 <Section title="今のつながりから、次のつながりを考える"><p>ここまでは、記録済みの関係を調べました。次は同じ6人について、<strong>「今はつながっていない2人が、この先、一緒に制作するだろうか？」</strong>と考えます。例えば、AとDには直接の辺がなくても、共通の共同制作者Cがいます。</p><p>共通の相手がいれば、必ず一緒に制作するのでしょうか。それを確かめるには、<strong>予測する時点のつながりを記録し、その後に何が起きたかを追う</strong>必要があります。この「予測するときの情報」と「後で分かった結果」が、次の章の入力と正解になります。</p><p className="note">次の章でも、C−Dを含む最初の7本の辺を出発点にします。グラフの話を、確率と学習の話につなげていきましょう。</p></Section>
 <Sources links={[graphSource,mathSource,["KH Coder：共起の指標と図の読み方","https://khcoder.net/FAQ.html"]]}/>
 </>;}

function Learning(){return <>
 <Section title="まだないつながりを、予測したい"><p>02の6人のグラフを続けます。最初の7本の辺に含まれない2人組は、全部で8組。その8組が、次の期間に共同制作したかを調べたとします。以下は<strong>仕組みを学ぶために作った架空の記録</strong>です。</p><p>予測前に分かる手がかりの一つが「共通の共同制作者がいるか」です。AとDなら共通するCがいるので1、AとEならいないので0。後で共同制作したら結果を1、しなかったら0と記録します。</p><Table head={['2人組','予測前：共通の共同制作者','その後：共同制作した']} rows={linkLearningPairs.map(r=>[r.pair,r.common?'いる（1）':'いない（0）',r.outcome?'した（1）':'しなかった（0）'])}/><p><strong>同じ「共通の相手がいる」でも、必ず共同制作するわけではありません。</strong>共通の相手がいた4組のうち、3組が共同制作し、1組はしませんでした。ここで、結果を確率で考える意味が出てきます。</p></Section>
 <Section title="「する／しない」の可能性を、割合から考える"><p>まず、共通の共同制作者がいた4組に条件をそろえます。「共同制作した」と「しなかった」は、同じ4組を二つに分けた内訳です。</p><DiscreteProbability/><p>こうした、区別できる結果に確率を付ける考え方が、離散確率を使った見方です。この例の3÷4＝0.75は観測した割合で、次の2人組にも必ず75%で当てはまると確認できたわけではありません。ほかの手がかりも使い、別の記録で確かめます。</p></Section>
 <Section title="入力と正解があるなら、教師あり学習"><p>「共通の相手がいる」「制作テーマが同じ」といった<strong>予測前に分かる情報を入力x</strong>にし、<strong>その後の共同制作の有無を正解y</strong>にします。この組を使って予測ルールを調整するのが、教師あり学習です。「教師」は、人が横で毎回答えるという意味ではありません。</p><Table head={['区分','この例では','注意']} rows={[["入力x","予測前の共通の共同制作者・制作テーマ","後でできたつながりを使わない"],["正解y","その後の共同制作：した1／しなかった0","予測値ではなく、記録した結果"],["モデルの出力p","この2人が共同制作する確率の予測","実際にそうなるかとは別"]]}/><p>後でできた辺まで使って「共通の相手」を数えると、未来の答えを先に見てしまいます。予測する時点をそろえることが大切です。同じ人が複数の組に登場するので、8組を独立した8人分と考えることもできません。</p></Section>
 <Section title="正解を付けないと、何を調べる？"><p>同じ6人のデータでも、「今後の共同制作」を正解として用意せず、関心やつながりが似た人を探すことはできます。こちらは<strong>教師なし学習</strong>の問題です。手法の違いの前に、何を知りたいかが違います。</p><Table head={['学習の種類','用意するもの','この例につなげると']} rows={[["教師あり学習","入力と正解の組","過去の記録から、今後共同制作するかを予測"],["教師なし学習","入力。予測用の正解は付けない","関心やつながりが似た人のまとまりを調べる"]]}/><p>次数や共通の相手を数えるだけなら、学習を使わずに計算できます。教師なし学習も、項目・距離・設定を人が決める必要があります。統計教材の<a href="#/statistics/method/cluster">クラスター分析</a>や<a href="#/statistics/method/tsne">t-SNE</a>も参照してください。</p><details><summary>ほかの学び方：強化学習と自己教師あり学習</summary><p><strong>強化学習</strong>は、行動の後の報酬も手がかりにして、どの行動を選ぶかを学ぶ方法です。<strong>自己教師あり学習</strong>は、文章の続きを予測するなど、データの一部から予測対象を作る方法です。ここではまず、入力と正解を明示した教師あり学習を追います。</p></details><Exercise question="共同制作の有無を正解にせず、関心の似た人を探すなら、教師あり・なしのどちら？" answer="教師なし学習です。その後に共同制作したかを正解にして予測ルールを調整するなら、教師あり学習になります。"/></Section>
 <Section title="次は、予測ルールの中身を見る"><p>次の04でも、この8組を使います。<strong>まず人が簡単なルールを作り、どの組で外れるかを見ます。</strong>そこから、入力に数を掛ける計算、ニューロン、ニューラルネットワークへ進みます。</p><p>0/1は入力や結果の区別です。予測確率や、これから使う重みは0.75や1.5のような連続的な値も取ります。すべての計算が0/1だけになるわけではありません。</p></Section>
 <Sources links={[["Deep Learning：確率・情報理論","https://www.deeplearningbook.org/contents/prob.html"],graphSource,["scikit-learn：教師なし学習","https://scikit-learn.org/stable/unsupervised_learning.html"]]}/>
 </>;}

function Networks(){const correct=linkLearningPairs.filter(r=>r.common===r.outcome).length;return <>
 <p className="lede">03で見た8組の共同制作を、同じ手がかりで予測してみます。まずは人がルールを作り、その計算の仕組みを一つずつ見ていきましょう。</p>
 <Section title="入力と正解を、もう一度並べる"><p>入力x₁は「共通の共同制作者がいるか」、入力x₂は「制作テーマが同じか」。ある・同じなら1、なければ0です。テーマは予測前に確認したもので、A・C・D・Fは家具、B・Eは映像とします。正解yは、その後に共同制作したかです。</p><Table head={['2人組','共通の相手 x₁','共通のテーマ x₂','その後の結果 y']} rows={linkLearningPairs.map(r=>[r.pair,r.common,r.topic,r.outcome])}/><p>A−Dなら入力は［1，1］、正解は1です。<strong>入力は予測するときに使う情報、正解は予測が合ったかを確かめる情報</strong>です。</p></Section>
 <Section title="まず、人が簡単なルールを作る"><p>「共通の共同制作者がいれば、今後共同制作する。いなければ、しない」と予測してみましょう。式なら、<strong>予測＝x₁</strong>です。</p><Table head={['2人組','ルールの予測','記録された正解','合っている？']} rows={linkLearningPairs.map(r=>[r.pair,r.common,r.outcome,r.common===r.outcome?'○':'×'])}/><p>{linkLearningPairs.length}組中{correct}組は合いましたが、B−EとC−Eで外れます。B−Eには共通の相手がいなくても、その後共同制作しています。C−Eには共通の相手がいても、していません。</p><p>ここで「テーマが同じかも考慮したら？」と考えられます。ただし、情報を足すだけで必ずよくなるとは限りません。<strong>ルールを変えたら、結果と照合する</strong>必要があります。</p></Section>
 <Section title="ルールを、入力に掛ける数で書く"><p>二つの手がかりを一緒に使うため、ひとまず「共通の相手あり」を2点、「共通のテーマあり」を1点として、合計してみます。これは説明用に人が仮に決めた配点です。</p><p className="note"><strong>点数＝2×x₁＋1×x₂</strong><br/>A−Dは2×1＋1×1＝3点。A−Fは2×0＋1×1＝1点。</p><p>入力に掛けた2や1を、<strong>重み</strong>と呼びます。どの手がかりをどれだけ計算に反映するかを決める数です。例えば2を1へ変えれば、共通の相手を持つ組の点数が下がります。</p><p>さらに「1.5点以上なら、共同制作すると予測する」という仮の基準を置きます。点数から1.5を引けば、0以上かどうかで判定できます。</p><p className="note"><strong>z＝2×x₁＋1×x₂−1.5</strong><br/>この−1.5のように、入力とは別に足す調整値が<strong>バイアス</strong>です。</p></Section>
 <Section title="点数を、0〜1の出力に直す"><p>判定を0か1で答えるだけでなく、「共同制作する確率をどのくらいと予測するか」を出したいとします。先ほどのzを、0〜1の値に変換するのが、ここで使う<strong>シグモイド関数</strong>です。</p><Table head={['zの値','変換後の出力 p（約）','この例での読み方']} rows={[[-1.5,.182,'共同制作する確率を約18%と予測'],[0,.5,'約50%と予測'],[1.5,.818,'約82%と予測']]}/><p>z＝0がp＝0.5に対応します。zを増やすとpも大きくなります。これは変換の仕組みであって、<strong>今の仮の配点が正しい予測確率を作れた、と確認したわけではありません。</strong></p><NeuronExplorer/></Section>
 <Section title="この小さな計算部品が、ニューロン"><p>ここまでの計算を一つの部品にまとめます。<strong>入力を受け取る → 重みを掛けて足す → バイアスを足す → 関数を通して出力する。</strong>この計算の単位が、ここでいうニューロンです。</p><p>最後に通す関数を<strong>活性化関数</strong>と呼びます。この例は出力を確率として使うためシグモイド関数を使いました。例えば途中で負の値だけを0にしたいなら、−2→0、0→0、3→3と変換する関数も使えます。この関数がReLU（Rectified Linear Unit）です。出力は3にもなるので、どのニューロンも確率を出すわけではありません。</p><p>入力の重み付き合計をシグモイド関数に通し、重みとバイアスをデータから学ぶ二値分類のモデルが、<strong>ロジスティック回帰</strong>です。今見た一つのニューロンと、同じ形の計算を使います。</p><p><strong>ここまでは人が重みを決めました。データに合わせて重みやバイアスを調整するのが、学習です。</strong>その方法は05で扱います。</p></Section>
 <Section title="一つの部品では、表せない規則もある"><p>ここまでの人の例では、記録していない事情も結果に関わります。次は部品の構造による違いだけを確かめるため、人のデータから離れ、01の<strong>XOR</strong>を使います。入力がどちらか一方だけ1なら、正解を1にする規則です。</p><div className="ai-xor-corners" role="img" aria-label="XORの4点。左上0・1は正解1、右上1・1は正解0、左下0・0は正解0、右下1・0は正解1。">{[[0,1,1],[1,1,0],[0,0,0],[1,0,1]].map(([a,b,y])=><div className={y?'ai-positive':''} key={`${a}${b}`}>入力（{a}，{b}）<br/><strong>正解 {y}</strong></div>)}</div><p>先ほどの一つのニューロンでは、入力を重み付きで足し、基準を超えるかで0／1を判定しました。その境界は、入力の図では一本の直線になります。XORでは1の点が対角にあるので、一本の直線で0と1を分けられません。</p></Section>
 <Section title="部品をつなぐと、ニューラルネットワークになる"><p>そこで、途中に複数の計算部品を置きます。最初の部品が入力の組み合わせから作った値を、次の部品が新しい入力として使います。こうしてつないだものが<strong>ニューラルネットワーク</strong>です。</p><p>例えばXORを、「少なくとも片方が1」と「両方が1」という二つの中間結果に分けてみます。前者だけが成り立つなら、XORは1です。</p><Table head={["入力","少なくとも片方が1","両方が1","前者だけなら1"]} rows={[["0・0",0,0,0],["0・1",1,0,1],["1・0",1,0,1],["1・1",1,1,0]]}/><p>この表は、計算を分担する考え方を0/1で示したものです。実際のニューロンは、先ほどの重みと活性化関数で連続的な中間値を作ります。途中で作った値を、次の計算の入力にする点が共通しています。</p><NetworkDiagram/><p>図では、入力x₁・x₂を受け取る二つの部品がh₁・h₂。その二つの結果から、最後の部品が出力pを作ります。途中のh₁・h₂が並ぶ場所を<strong>隠れ層（中間層）</strong>、答えを出す場所を<strong>出力層</strong>と呼びます。</p><p>間に非線形の活性化関数を入れると、XORのような規則も表せます。掛け算と足し算だけを重ねても、全体は一つの線形な変換にまとめられるため、層を増やすだけでは足りません。</p><p>このように前から後ろへ計算するモデルを<strong>順伝播型ニューラルネットワーク</strong>と呼び、多層パーセプトロン（MLP）はその代表例です。次の章では、図の各部品の重みを、XORの4通りから実際に学習させます。</p><Exercise question="入力2個、隠れ層2個、出力1個のこの図で、学習する数はいくつ？" answer="入力→隠れ層の重み4個とバイアス2個、隠れ層→出力の重み2個とバイアス1個。合計9個です。"/></Section>
 <Sources links={[networkSource,["scikit-learn：MLPの構造と活性化関数","https://scikit-learn.org/stable/modules/neural_networks_supervised.html"]]}/>
 </>;}

function Training(){return <>
 <Section title="予測して、間違いを測り、重みを直す"><p>04では、重みとバイアスを人が仮に決めました。ここではXORの入力と正解を使い、図の9個の数を調整していきます。最初に仮の値を入れ、次の順番を繰り返します。</p><ol className="exercise-list"><li><strong>まず予測する。</strong>今の重みで、入力から答えを計算する。</li><li><strong>正解と比べる。</strong>どのくらい外れたか、点数を付ける。</li><li><strong>直す向きを調べる。</strong>各重みを増やす・減らすと、その点数がどう変わるか計算する。</li><li><strong>少し直して、もう一度試す。</strong>外れ方が小さくなる向きへ重みを動かす。</li></ol><p>この後で、一つずつ計算しながら正式名称を付けていきます。</p></Section>
 <Section title="損失は、強く外した予測ほど大きくする"><p>実際には成功したのに「成功の確率は10%」と予測したら、大きく外しています。「成功は90%」なら、小さな外れです。この外れ方を測る点数が<strong>損失</strong>です。小さいほど、正解によく合っています。</p><p>以下は、正解に付けた確率が低いほど大きくなる点数の例です。まず数の違いを見てください。</p><Table head={['正解','出力p','その正解に付けた確率','損失（約）']} rows={[[1,.9,.9,.105],[1,.5,.5,.693],[1,.1,.1,2.303],[0,.9,.1,2.303]]}/><p>この点数の計算が<strong>二値交差エントロピー</strong>です。正解が1なら−log(p)、正解が0なら−log(1−p)。logは自然対数です。まずは「正解に付けた確率が小さいほど、大きい損失になる」と押さえます。</p><p>正解が1のとき、p＝0.9とp＝0.51は、どちらも0.5を超えます。それでも予測した確率は違うので、損失も違います。学習では、この確率の違いも使って重みを調整します。</p></Section>
 <Section title="微分：少し動かしたら、損失はどう変わる？"><p>まず、重みがwの一つだけで、損失が<strong>L＝（w−2）²</strong>という練習用の関数を考えます。ニューラルネットワークの損失をそのまま表したものではありません。</p><Table head={['重みw',0,1,2,3]} rows={[["損失L",4,1,0,1]]}/><p>w＝1から少し増やすと損失は下がり、w＝3から少し増やすと損失は上がります。この、<strong>その場所での変わり方（傾き）</strong>を求めるのが微分です。微分して得た関数を<strong>導関数</strong>といい、この例ではL′＝2（w−2）。w＝1なら−2、w＝3なら＋2です。</p><p>重みが何個もあるときは、ほかを固定し、一つの重みについて変わり方を求めます。これが<strong>偏微分</strong>。各重みについての偏微分を並べたものが<strong>勾配</strong>です。</p></Section>
 <Section title="つながった計算を、後ろからたどる"><p>例えば、途中の値h＝2w、最後の損失L＝（h−4）²とします。wからLへ、hを経由する二段階の計算です。w＝1ならh＝2、L＝4です。</p><Table head={['どこの変わり方？','計算','w＝1のとき']} rows={[["wを変えたときのh","h＝2wの傾きは2",2],["hを変えたときのL","（h−4）²の傾きは2（h−4）",-4],["wを変えたときのL","途中ごとの傾きを掛ける：2×（−4）",-8]]}/><p>こうして、つながった計算の変わり方を、<strong>途中の傾きの掛け算で求める</strong>のが<strong>連鎖律</strong>です。計算が枝分かれしていれば、それぞれの経路から来る分を足します。</p><p><strong>誤差逆伝播（バックプロパゲーション）</strong>は、この考え方で出力側から順に各重みの勾配を求める計算です。どの重みをどう動かすと損失が下がるかを、途中の計算も含めて調べられます。</p></Section>
 <Section title="勾配と学習率：どちらへ、どのくらい動かす？"><p>勾配の各成分は、それぞれの重みを少し増やしたときの、損失の変わり方を表します。勾配降下法では、その逆向きに動かします。</p><p className="note"><strong>新しい重み＝今の重み−学習率×勾配</strong><br/>今の重み0.4、勾配0.3、学習率0.1なら、0.4−0.1×0.3＝0.37です。</p><p><strong>学習率</strong>は、一度に動かす大きさを調整する数です。大きすぎると行き過ぎ、小さすぎると進みが遅くなることがあります。誤差逆伝播は勾配を求める計算、勾配降下法はその勾配を使って更新する方法です。</p><p>入力から順に予測を計算するのが<strong>順伝播</strong>、後ろから勾配を求めるのが<strong>誤差逆伝播</strong>、その勾配を使って重みを直す方法の一つが<strong>勾配降下法</strong>です。下のボタンで、この一巡を繰り返せます。</p><NetworkDiagram/><TrainingExplorer/><p>この例は4行すべてから勾配を求め、1回更新します。全データを一巡する単位を<strong>エポック</strong>、一度の計算にまとめるデータを<strong>バッチ</strong>と呼びます。データを小さなバッチに分ける場合、1エポックの中で何度も更新します。</p></Section>
 <OverfittingLesson/>
 <Sources links={[trainingSource,prerequisitesSource,["Google：過学習と学習経過の見方","https://developers.google.com/machine-learning/crash-course/overfitting/overfitting"],["scikit-learn：検証用・テスト用の分割","https://scikit-learn.org/stable/modules/cross_validation.html"]]}/>
 </>;}

function DownloadExample({id,csv,packages}){return <><div className="download-row"><a href={`${base}data/ai/${csv}`} download>入力CSVを保存 ↓</a><a href={`${base}data/ai/${id}.py`} download>Pythonコードを保存 ↓</a></div><LocalPythonCommands packages={packages} filename={`${id}.py`}/><details><summary>確認用のPythonコード</summary><pre className="code-block"><code>{examples[id].code}</code></pre></details><details><summary>このコードの実行結果</summary><pre className="code-block"><code>{examples[id].output}</code></pre></details></>;}
const pages=[Discrete,Graphs,Learning,Networks,Training,Practice,Architectures,PretrainedModels];
export default function AiCourse({route}){const index=aiLinks.findIndex(([path])=>path===route);if(index<0)return <><h1>ページが見つかりません</h1><a href="#/ai">人工知能学習入門へ戻る</a></>;const Page=pages[index];return <><p className="eyebrow">人工知能学習入門 / {String(index+1).padStart(2,'0')}</p><h1>{aiLinks[index][1].replace(/^\d+　/,'')}</h1><Page/>{index<aiLinks.length-1?<Next href={aiLinks[index+1][0]} label={`${aiLinks[index+1][1]}へ進む`}/>:<Next href="/ai-intro" label="続きの「AI入門」へ進む"/>}</>;}
