import { useState } from 'react';
import { adjacency,graphNodes,graphEdges,linkLearningPairs,sigmoid,initialNetwork,forwardNetwork,networkLoss,trainNetwork,xorData } from './aiMath.js';

const positions=[[75,65],[75,215],[190,140],[330,140],[445,65],[445,215]];
export function GraphExplorer(){
 const [bridge,setBridge]=useState(true),[selected,setSelected]=useState(2),a=adjacency(bridge);
 const neighbors=graphNodes.filter((_,i)=>a[selected][i]),common=graphNodes.filter((_,i)=>a[0][i]&&a[3][i]);
 return <div className="explorer"><h3>6人の「共同制作したことがある」を表す</h3><p>架空の6人です。ここでは、AがBと共同制作したらBもAと共同制作しているので、矢印のない<strong>無向グラフ</strong>で表します。</p><div className="segmented" role="group" aria-label="調べる頂点">{graphNodes.map((name,i)=><button key={name} aria-pressed={i===selected} onClick={()=>setSelected(i)}>{name}を調べる</button>)}</div><label className="ai-toggle"><input type="checkbox" checked={bridge} onChange={e=>setBridge(e.target.checked)}/> CとDの共同制作を含める</label><svg className="plot ai-graph" viewBox="0 0 520 285" role="img" aria-label={`${graphEdges(bridge).length}本の辺があるグラフ。${graphNodes[selected]}と直接つながるのは${neighbors.join('・')}。`}>{graphEdges(bridge).map(([i,j])=><line key={`${i}-${j}`} x1={positions[i][0]} y1={positions[i][1]} x2={positions[j][0]} y2={positions[j][1]} stroke={i===2&&j===3?'#cc2939':'#8993a1'} strokeWidth="3"/>)}{positions.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="23" fill={i===selected?'#cc2939':'white'} stroke={a[selected][i]?'#cc2939':'#333'} strokeWidth="2"/><text x={x} y={y+6} textAnchor="middle" style={{fill:i===selected?'white':'#111'}}>{graphNodes[i]}</text></g>)}</svg><p aria-live="polite"><strong>{graphNodes[selected]}の隣接頂点：｛{neighbors.join('，')}｝。次数：{neighbors.length}。</strong><br/>隣接頂点は直接つながる相手、次数はつながる辺の本数です。</p><div className="table-scroll"><table className="data-table ai-adjacency"><caption>隣接行列：直接つながるなら1、つながらないなら0</caption><thead><tr><th>行 ↓ ／ 列 →</th>{graphNodes.map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{a.map((row,i)=><tr key={i} className={selected===i?'ai-selected-row':''}><th>{graphNodes[i]}</th>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div><p>行A・列Dは0です。直接のつながりはありません。{bridge?'ただしA→C→Dと2本の辺をたどれます。':'C−Dを外すと、A側とD側の間をたどれなくなります。'}<strong> AとDの共通の隣接頂点は{common.length}人{common.length?`（${common.join('・')}）`:''}</strong>です。</p></div>;
}

export function DiscreteProbability(){
 const selectedPairs=linkLearningPairs.filter(row=>row.common);
 const total=selectedPairs.length;
 const [chosen,setChosen]=useState(()=>selectedPairs.filter(row=>row.outcome).length),notChosen=total-chosen;
 const probability=chosen/total,otherProbability=notChosen/total;
 return <div className="explorer">
  <h3>条件をそろえて、割合を数える</h3>
  <p>対象は、共通の共同制作者がいた<strong>{total}組（{selectedPairs.map(row=>row.pair).join('、')}）</strong>です。最初は上の記録どおり3組と1組。スライダーでは「結果の内訳が違ったら」と試せます。</p>
  <label className="control">共同制作した組数：{chosen}組<input type="range" min="0" max={total} step="1" value={chosen} onChange={e=>setChosen(+e.target.value)}/></label>
  <label className="control">共同制作しなかった組数：{notChosen}組<input type="range" min="0" max={total} step="1" value={notChosen} onChange={e=>setChosen(total-Number(e.target.value))}/></label>
  <p>どちらを動かしても、もう片方が連動します。<strong>同じ{total}組の内訳なので、合計はいつも{total}組です。</strong></p>
  <svg className="plot" viewBox="0 0 500 210" role="img" aria-label={`${total}組の内訳。共同制作した${chosen}組・${probability*100}%、しなかった${notChosen}組・${otherProbability*100}%。合計100%。`}>
   <text x="25" y="30">{total}組の内訳：1マスが1組</text>
   {Array.from({length:total},(_,i)=><rect key={i} x={25+i*112} y="52" width="105" height="44" rx="3" fill={i<chosen?'#cc2939':'#2865b0'}/>)}
   <rect x="25" y="124" width="16" height="16" fill="#cc2939"/><text x="52" y="139">共同制作した：{chosen}組（{probability*100}%）</text>
   <rect x="25" y="166" width="16" height="16" fill="#2865b0"/><text x="52" y="181">しなかった：{notChosen}組（{otherProbability*100}%）</text>
  </svg>
  <div aria-live="polite"><p><strong>P（した｜共通の相手あり）＝{chosen} ÷ {total}＝{probability.toFixed(2)}</strong><br/><strong>P（しなかった｜共通の相手あり）＝{notChosen} ÷ {total}＝{otherProbability.toFixed(2)}</strong></p><p className="note"><strong>{probability.toFixed(2)} ＋ {otherProbability.toFixed(2)} ＝ 1（100%）</strong><br/>「しなかった」の割合は、1から「した」の割合を引いたものです。</p></div>
  <p>ここでのPは、対象の4組から1組を等しい確率で選んだときの確率です。「｜共通の相手あり」は、対象を絞る条件を表します。まだ調べていない組の確率を、そのまま確定したものではありません。</p>
 </div>;
}

export function NeuronExplorer(){
 const [x1,setX1]=useState(1),[x2,setX2]=useState(0),[w1,setW1]=useState(2),[w2,setW2]=useState(1),[bias,setBias]=useState(-1.5);
 const z=w1*x1+w2*x2+bias,p=sigmoid(z),curve=Array.from({length:101},(_,i)=>{const x=-9+i*.18;return `${i?'L':'M'}${50+(x+9)*(384/18)},${200-sigmoid(x)*150}`;}).join(' ');
 return <div className="explorer"><h3>入力に重みを掛けて、足す</h3><p>左の入力x₁は「共通の共同制作者がいる」、右の入力x₂は「制作テーマが同じ」。当てはまるなら1です。例えばA−Dは入力1・1、A−Fは0・1です。</p><div className="segmented" role="group" aria-label="ニューロンの入力">{[[0,0],[0,1],[1,0],[1,1]].map(([a,b])=><button key={`${a}${b}`} aria-pressed={x1===a&&x2===b} onClick={()=>{setX1(a);setX2(b);}}>入力 {a}・{b}</button>)}</div>{[['重み w₁',w1,setW1],['重み w₂',w2,setW2],['バイアス b',bias,setBias]].map(([name,value,setter])=><label className="control" key={name}>{name}：{value.toFixed(1)}<input type="range" min="-3" max="3" step=".1" value={value} onChange={e=>setter(+e.target.value)}/></label>)}<p aria-live="polite"><strong>z＝{w1.toFixed(1)}×{x1}＋{w2.toFixed(1)}×{x2}＋（{bias.toFixed(1)}）＝{z.toFixed(1)}</strong><br/>シグモイド関数を通すと、出力p＝<strong>{p.toFixed(4)}（約{(p*100).toFixed(2)}%）</strong>。</p><svg className="plot" viewBox="0 0 490 255" role="img" aria-label={`シグモイド関数。入力の加重和${z.toFixed(1)}を、予測確率${p.toFixed(3)}へ変換。`}><line x1="50" x2="440" y1="200" y2="200" stroke="#aaa"/><line x1="50" x2="440" y1="125" y2="125" stroke="#ddd"/><path d={curve} fill="none" stroke="#cc2939" strokeWidth="3"/><circle cx={50+(z+9)*(384/18)} cy={200-p*150} r="6" fill="#111"/><text x="18" y="205">0</text><text x="8" y="130">0.5</text><text x="18" y="55">1</text><text x="50" y="222">−9</text><text x="242" y="222" textAnchor="middle">0</text><text x="434" y="222" textAnchor="end">9</text><text x="245" y="249" textAnchor="middle">重み付きの合計 z</text><text x="50" y="25">出力 p</text></svg><p>この図では、出力を「その後に共同制作する確率」の予測値として使います。<strong>バイアス</strong>は入力とは別に足す調整値です。ここで手で動かした重み・バイアスを、データから決めるのが学習です。</p></div>;
}

export function NetworkDiagram(){return <figure className="ai-network"><svg viewBox="0 0 540 270" role="img" aria-label="入力2個、隠れ層のニューロン2個、出力1個の全結合ニューラルネットワーク。矢印は入力から出力へ計算が進む向き。"><defs><marker id="ai-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10z" fill="#8993a1"/></marker></defs>{[85,190].flatMap(y=>[85,190].map(t=><line key={`${y}-${t}`} x1="103" y1={y} x2="240" y2={t} stroke="#8993a1" strokeWidth="2" markerEnd="url(#ai-arrow)"/>))}{[85,190].map(y=><line key={y} x1="295" y1={y} x2="430" y2="138" stroke="#8993a1" strokeWidth="2" markerEnd="url(#ai-arrow)"/>)}{[[75,85,'x₁'],[75,190,'x₂'],[270,85,'h₁'],[270,190,'h₂'],[460,138,'p']].map(([x,y,label])=><g key={label}><circle cx={x} cy={y} r="27" fill="white" stroke="#cc2939" strokeWidth="2"/><text x={x} y={y+7} textAnchor="middle">{label}</text></g>)}<text x="75" y="30" textAnchor="middle">入力</text><text x="270" y="30" textAnchor="middle">隠れ層</text><text x="460" y="30" textAnchor="middle">出力</text><text x="270" y="254" textAnchor="middle">それぞれで「重みを掛ける → 足す → 関数を通す」</text></svg></figure>;}

const freshTraining=()=>{const model=initialNetwork();return {model,steps:0,history:[[0,networkLoss(model)]]};};
export function TrainingExplorer(){
 const [state,setState]=useState(freshTraining),[rate,setRate]=useState(1);
 function advance(count){setState(previous=>{let model=previous.model;const end=Math.min(previous.steps+count,5000),history=[...previous.history];for(let i=previous.steps+1;i<=end;i++){model=trainNetwork(model,rate);if(i%10===0||i===end)history.push([i,networkLoss(model)]);}return {model,steps:end,history};});}
 const loss=networkLoss(state.model),correct=xorData.filter(row=>(forwardNetwork(state.model,row).p>=.5?1:0)===row[2]).length;
 const path=state.history.map(([x,y],i)=>`${i?'L':'M'}${55+x/Math.max(state.steps,1)*400},${215-Math.min(y,1)*170}`).join(' ');
 return <div className="explorer"><h3>XORの4通りを、実際に学習する</h3><p>入力2個・隠れ層2個・出力1個。全ニューロンにシグモイド関数を使い、4行の平均損失を小さくします。ボタンを押すと、画面内で勾配を計算して重みを更新します。</p><label className="control">学習率：{rate.toFixed(2)}<input type="range" min=".05" max="2" step=".05" value={rate} onChange={e=>setRate(+e.target.value)}/></label><div className="segmented">{[1,100,1000].map(n=><button key={n} disabled={state.steps>=5000} onClick={()=>advance(n)}>{n}回学習する</button>)}<button onClick={()=>{setState(freshTraining());setRate(1);}}>最初に戻す</button></div><p aria-live="polite"><strong>更新{state.steps}回／平均損失 {loss.toFixed(4)}／4通り中{correct}通り正解</strong></p><svg className="plot" viewBox="0 0 500 270" role="img" aria-label={`${state.steps}回までの学習曲線。平均損失${loss.toFixed(4)}。`}><line x1="55" x2="455" y1="215" y2="215" stroke="#aaa"/>{[0,.5,1].map(y=><g key={y}><line x1="55" x2="455" y1={215-y*170} y2={215-y*170} stroke="#ddd"/><text x="43" y={220-y*170} textAnchor="end">{y}</text></g>)}<path d={path} stroke="#cc2939" strokeWidth="3" fill="none"/><text x="55" y="25">平均損失</text><text x="55" y="244">0</text><text x="455" y="244" textAnchor="end">{state.steps}</text><text x="250" y="266" textAnchor="middle">重みを更新した回数</text></svg><div className="table-scroll"><table className="data-table"><thead><tr><th>入力x₁</th><th>入力x₂</th><th>正解y</th><th>出力p</th><th>p≧0.5で判定</th></tr></thead><tbody>{xorData.map(([a,b,y])=>{const p=forwardNetwork(state.model,[a,b]).p;return <tr key={`${a}${b}`}><td>{a}</td><td>{b}</td><td>{y}</td><td>{p.toFixed(3)}</td><td>{p>=.5?1:0}</td></tr>;})}</tbody></table></div><details><summary>今の重みとバイアスを見る</summary><p>入力→h₁：重み（{state.model.w1[0].map(v=>v.toFixed(3)).join('，')}）、b＝{state.model.b1[0].toFixed(3)}</p><p>入力→h₂：重み（{state.model.w1[1].map(v=>v.toFixed(3)).join('，')}）、b＝{state.model.b1[1].toFixed(3)}</p><p>隠れ層→出力：重み（{state.model.w2.map(v=>v.toFixed(3)).join('，')}）、b＝{state.model.b2.toFixed(3)}</p></details><p>これは4通りの真理値表を学ぶ計算実験です。<strong>学習に使った4行の正解率であり、未知データの性能評価ではありません。</strong>初期値・学習率・構造によって、学習の進み方は変わります。</p></div>;
}
