// Primary publications and the institutions responsible for the collections or methods.
export const designStudySources = {
  ashizawaHistory: { name: '蘆澤雄亮：超ザックリ版「デザインの歴史」', url: 'https://note.com/yashizawa/n/nb3dbf1e3b3a3', note: '本教材の歴史を読む軸。量産と品質、ローウィとドレフュス、デザイン思考のつながりを考える。' },
  ashizawaUx: { name: '蘆澤雄亮：UXの謎にせまる', url: 'https://note.com/yashizawa/n/n9698ba770750', note: '人間工学、メンタルモデル、時間とともに変わる経験を考える入口。' },
  ashizawaDialogue: { name: '蘆澤雄亮：対話するデザイン', url: 'https://note.com/yashizawa/n/n90b9efdb8393', note: '誰のために、誰と考えるのか。対話する相手の広がりから歴史を読む。' },
  werkbund: { name: 'Werkbundarchiv – Museum der Dinge：ドイツ工作連盟の年表', url: 'https://museumderdinge.de/ueber-uns/deutscher-werkbund/geschichte-des-deutschen-werkbunds/chronologie-des-deutschen-werkbunds/', note: '1907年の設立と、美術・工芸・産業を結び付けた活動。' },
  gmDesign: { name: 'GM News：How GM Invented the Concept Car and Changed Automotive Design Forever', url: 'https://news.buick.com/newsroom.detail.html/Pages/topic/us/en/2026/may/0529-gm-invented-concept-car-changed-automotive-design.html', note: 'GMによる歴史解説。1927年のArt and Colour SectionとHarley Earl、技術者との協働や粘土模型を使った設計を確認する。' },
  dschool: { name: 'Stanford d.school：Design Thinking Bootleg', url: 'https://dschool.stanford.edu/tools/design-thinking-bootleg', note: '共感・問題定義・発想・試作・テストの5つの活動。固定された一方向の手順ではなく、途中から始め、行き来できる。' },
  loewy: { name: 'Raymond Loewy公式サイト：Quotes', url: 'https://www.raymondloewy.com/about/quotes/', note: 'MAYA（Most Advanced Yet Acceptable）という考え方。' },
  dreyfuss: { name: 'Cooper Hewitt, Smithsonian Design Museum：The 302', url: 'https://www.cooperhewitt.org/2013/10/24/the-302/', note: '電話機302（1937年）と500（1949年）の設計背景。' },
  dreyfussArchive: { name: 'Smithsonian：Henry Dreyfuss Collection', url: 'https://www.si.edu/object/archives/sova-sil-ch-1972-88-332-4', note: '人体寸法への取り組みと、Designing for People（1955年）などの著書。' },
  uxOrigins: { name: 'Donald A. Norman：Where Did the Term User Experience (UX) Come From?', url: 'https://jnd.org/where-did-the-term-user-experience-ux-come-from/', note: '用語の起源をめぐる本人の説明。1993年のApple入社後の活動と、それ以前の使用例を区別する。' },
  uxWhitePaper: { name: 'Roto・Law・Vermeeren・Hoonhout編（2011）：User Experience White Paper', url: 'https://experienceresearchsociety.org/wp-content/uploads/2023/01/UX-WhitePaper.pdf', note: '2010年の研究者会合に基づく2011年の文書。経験の時間的な広がりと、人・システム・状況の関係。' },
  universal: { name: 'NC State University（1997）：The Principles of Universal Design', url: 'https://design.ncsu.edu/wp-content/uploads/2022/11/principles-of-universal-design.pdf', note: 'ユニバーサルデザインの定義と7原則。原則名の日本語は本教材での説明。' },
  inclusive: { name: 'Royal College of Art：Helen Hamlyn Centre for Design', url: 'https://www.rca.ac.uk/research-innovation/research-centres/helen-hamlyn-centre/about-centre/', note: 'DesignAge（1991年）、Colemanによる提唱（1994年）、研究センターの正式設立（1999年）。' },
  crossThinking: { name: 'Nigel Cross（2023）：Design Thinking: What Just Happened?', url: 'https://oro.open.ac.uk/88602/1/1-s2.0-S0142694X23000285-main.pdf', note: 'Design Studies, 86, 101187。著者所属大学の公開原文。3.1節の原語はDesignThinking 1／2。本教材の1.0／2.0表記はこの区別を指す。批判の整理は2.1節、今後の可能性は結論を参照。' },
  ideoCart: { name: 'IDEO：Reimagining the Shopping Cart', url: 'https://www.ideo.com/journal/reimagining-the-shopping-cart', note: '1999年のNightlineで紹介された試作の事例。ページ公開年の2000年と放送年を区別する。' },
  brown: { name: 'Tim Brown（2008）：Design Thinking', url: 'https://hbr.org/2008/06/design-thinking', note: 'Harvard Business Review、2008年6月号。出版元の書誌・概要。本文の閲覧に購読が必要な場合がある。' },
  ideoThinking: { name: 'IDEO：Design Thinking — Introduction', url: 'https://designthinking.ideo.com/introduction', note: 'IDEO自身による説明。人にとっての望ましさ、技術的な実現可能性、事業としての成立を重ねる考え方と、普及への関わり。' },
  ideoAbout: { name: 'IDEO：About Us', url: 'https://www.ideo.com/about', note: 'IDEOの実践と普及の説明。Tim BrownのChange by Design（2009年）も紹介する。' },
  kelleyEducation: { name: 'David Kelley：Design Lessons from the Stanford d.school', url: 'https://www.ideo.com/journal/ideo-founder-david-kelley-shares-design-lessons-from-the-stanford-d-school', note: '設立に関わった本人による、異分野の人が学ぶ場としてのd.schoolと教材公開の説明。' },
  jssdMotorcycle: { name: '片山陽次郎ほか（1967）：2輪自動車デザインに関する人間工学的一考察', url: 'https://doi.org/10.11247/jssdj.1967.63', note: 'デザイン学研究, 1967(6), 63–64。ハンドルなどの位置と操作・姿勢の研究。' },
  jssdCircle: { name: '角田専一郎（1968）：SYMBOL DESIGNにおける円形の展開について', url: 'https://doi.org/10.11247/jssdj.1968.10', note: 'デザイン学研究, 1968(8), 10–11。図形の作例を通じた造形の考察。' },
  jssdSociety: { name: '宮崎清（1968）：大量生産品の社会に与える効果,ならびに,受容者の社会心理的局面に関する考察', url: 'https://doi.org/10.11247/jssdj.1968.30', note: 'デザイン学研究, 1968(8), 30–31。電気釜・冷蔵庫が地域の生活の中で受け入れられる過程。' },
  buchanan: { name: 'Richard Buchanan（1992）Wicked Problems in Design Thinking', url: 'https://web.mit.edu/jrankin/www/engin_as_lib_art/Design_thinking.pdf', note: 'Design Issues, 8(2), 5–21。MITの授業用ページに置かれた原論文。特に16〜19頁で、デザインの対象があらかじめ固定されないことと、立場の多様性を論じる。' },
  jssd: { name: '日本デザイン学会：研究部会・支部', url: 'https://jssd.jp/about/section-and-branch', note: 'デザインを研究する分野の広がりを確認する。' },
  cross: { name: 'Nigel Cross（1982）Designerly Ways of Knowing', url: 'https://doi.org/10.1016/0142-694X(82)90040-0', note: 'Design Studies, 3(4), 221–227。出版社の書誌・抄録。デザインに固有の知り方を考える原論文。' },
  simon: { name: 'Herbert A. Simon：The Sciences of the Artificial', url: 'https://mitpress.mit.edu/9780262354752/the-sciences-of-the-artificial/', note: 'MIT Press。リンク先は第3版（1996）の2019年再刊版。人工物や設計を研究対象として捉える本。' },
  wdo: { name: 'World Design Organization：Definition of Industrial Design', url: 'https://wdo.org/about/definition/', note: 'インダストリアルデザインの定義。デザイン全領域の唯一の定義ではない。' },
  arts: { name: 'V&A：Arts and Crafts: an Introduction', url: 'https://www.vam.ac.uk/articles/arts-and-crafts-an-introduction', note: '美術館の解説。生産の仕方や労働と、ものの質との関係を読む。' },
  bauhaus: { name: 'Bauhaus-Archiv：Das Bauhaus', url: 'https://www.bauhaus.de/de/das_bauhaus/', note: 'バウハウス資料館。1919〜1933年の学校の歴史。ドイツ語。' },
  mingei: { name: '日本民藝館：沿革', url: 'https://mingeikan.or.jp/about/history/?lang=ja', note: '1925年の「民藝」の命名と、1936年の開館などを確認する。' },
  ulm: { name: 'HfG-Archiv／Museum Ulm：ウルム造形大学', url: 'https://hfg-archiv.museumulm.de/', note: '大学の資料を保存する機関。1953〜1968年の学校と、その社会的な目標。ドイツ語。' },
  gmark: { name: '日本デザイン振興会：グッドデザイン賞の歴史', url: 'https://www.g-mark.org/learn/gda/history', note: '1957年に始まった制度と、日本の産業・社会との関係。' },
  drs: { name: 'Design Research Society：History', url: 'https://www.designresearchsociety.org/cpages/history', note: '1962年のデザイン方法の会議、1966年の学会設立、1971年の参加を扱った会議。' },
  postmodern: { name: 'V&A：What Is Postmodernism?', url: 'https://www.vam.ac.uk/articles/what-is-postmodernism', note: '1970〜1990年頃のデザインを、複雑さ・矛盾・引用から読む。' },
  norman: { name: 'Donald A. Norman（2008）Signifiers, Not Affordances', url: 'https://jnd.org/signifiers-not-affordances/', note: '著者公開の原稿。アフォーダンスと、行為の手がかりとなるシグニファイアを区別する。' },
  affordances: { name: 'Donald A. Norman：Affordances and Design', url: 'https://jnd.org/affordances-and-design/', note: 'Gibsonの概念と、実際にできる行為・知覚される手がかりの違いを、著者自身が解説する。' },
  nielsenUsability: { name: 'Jakob Nielsen：Usability 101 — Introduction to Usability', url: 'https://www.nngroup.com/articles/usability-101-introduction-to-usability/', note: 'ユーザビリティの5つの構成要素と、利用者の操作を観察する方法。' },
  nielsenHeuristics: { name: 'Jakob Nielsen：10 Usability Heuristics for User Interface Design', url: 'https://www.nngroup.com/articles/ten-usability-heuristics/', note: 'ニールセンによる10原則の説明。本文は教材独自の予約画面の例で整理したもの。' },
  gestaltOriginal: { name: 'Max Wertheimer（1923／英訳1938）：Laws of Organization in Perceptual Forms', url: 'https://www.yorku.ca/pclassic/Wertheimer/Forms/forms.htm', note: '近接・類同・よい連続など、知覚のまとまりを扱う原論文の英訳。' },
  gestaltVisual: { name: 'Nielsen Norman Group：Visual Design — Glossary', url: 'https://www.nngroup.com/articles/visual-design-cheat-sheet/', note: '近接・類同・閉合・よい連続・図と地などの視覚的な原理と用語。図は教材独自の模式図。' },
  commonRegion: { name: 'Nielsen Norman Group：The Principle of Common Region', url: 'https://www.nngroup.com/articles/common-region/', note: '後に加わった群化の原理である共通領域を、カードや囲みなどのUIへの応用から説明する。' },
  communication: { name: 'Donald A. Norman：Affordance, Conventions and Design (Part 2)', url: 'https://jnd.org/affordance-conventions-and-design-part-2/', note: '概念モデル、慣習、フィードバックと、実際の利用場面を観察する必要性。' },
  codesign: { name: 'Elizabeth B.-N. Sanders・Pieter Jan Stappers（2008）Co-creation and the New Landscapes of Design', url: 'https://studiolab.io.tudelft.nl/manila/gems/contextmapping/PreprintDraft.pdf', note: '著者所属大学が公開する投稿原稿。刊行版はCoDesign, 4(1), 5–18。利用者とともにつくる考え方。' },
  hcd: { name: 'ISO 9241-210:2019：Human-centred Design for Interactive Systems', url: 'https://www.iso.org/standard/77520.html', note: '対話型システムの人間中心設計を扱う規格。リンク先の概要は無料、規格本文は有料。' },
  diamond: { name: 'Design Council：Framework for Innovation', url: 'https://www.designcouncil.org.uk/resources/framework-for-innovation/', note: 'ダブルダイヤモンドの提唱団体による説明。広げる・絞ることと、反復を確認する。' },
  systemic: { name: 'Design Council：Systemic Design Framework', url: 'https://www.designcouncil.org.uk/resources/systemic-design-framework/', note: '社会や環境とのつながりを扱う、システミックデザインの枠組み。' },
  frayling: { name: 'Christopher Frayling（1993/94）Research in Art and Design', url: 'https://researchonline.rca.ac.uk/384/', note: 'Royal College of Art Research Papers, 1(1)。大学公開の原文と書誌。制作と研究の関係を考える。' },
};
