export const dtpSources = {
  layout: ['Adobe：レイアウトの基本', 'https://www.adobe.com/learn/illustrator/web/layout-basics'],
  units: ['モリサワ：文字に関する単位', 'https://note.morisawa.co.jp/n/nf63dc1bd449b'],
  kerning: ['Adobe：カーニングとトラッキング', 'https://helpx.adobe.com/jp/indesign/desktop/format-and-style-text/tabs-indents-and-spacing/about-kerning-and-tracking.html'],
  spacing: ['モリサワ：文字詰め機能の違い', 'https://note.morisawa.co.jp/n/nb96702245df1'],
  leading: ['モリサワ：行間と行送り', 'https://note.morisawa.co.jp/n/n2b06edcb3a45'],
  kinsoku: ['モリサワ：禁則処理', 'https://note.morisawa.co.jp/n/nc9e6aac69336'],
  typesetting: ['JAGAT：版面の設計', 'https://www.jagat.or.jp/archives/25594'],
  color: ['Adobe：RGB・CMYKなどのカラーモデル', 'https://helpx.adobe.com/jp/creative-cloud/apps/colors/understand-color-modes.html'],
  colorManagement: ['Adobe：カラーマネジメントを使用したプリント', 'https://helpx.adobe.com/jp/illustrator/using/printing-color-management.html'],
  resolution: ['Adobe：プリント画像の解像度', 'https://helpx.adobe.com/jp/photoshop/desktop/crop-resize-transform/resize-adjust-resolution/printed-image-resolution.html'],
  resampling: ['Adobe：サイズ変更と再サンプル', 'https://helpx.adobe.com/photoshop/kb/advanced-cropping-resizing-resampling-photoshop.html'],
  imageTypes: ['Adobe：ラスターとベクター', 'https://www.adobe.com/creativecloud/file-types/image/comparison/raster-vs-vector.html'],
  paths: ['Adobe：パスと図形の基本', 'https://helpx.adobe.com/jp/illustrator/using/artwork-essentials/paths-and-shapes.html'],
  pathEditing: ['Adobe：パスの調整', 'https://helpx.adobe.com/jp/illustrator/desktop/draw-shapes-and-paths/modify-paths/refine-paths.html'],
  outline: ['Adobe：文字のアウトライン化', 'https://helpx.adobe.com/jp/illustrator/web/add-and-edit-artwork/create-text/create-outline-text.html'],
  rasterize: ['Adobe：ラスタライズ効果', 'https://helpx.adobe.com/jp/illustrator/using/effects.html'],
  trace: ['Adobe：画像トレースの結果と元画像の品質', 'https://helpx.adobe.com/jp/illustrator/using/image-trace-results-optimization.html'],
  bleed: ['Adobe：裁ち落とし領域とトンボ', 'https://helpx.adobe.com/jp/indesign/desktop/print/page-set-up-and-printer-marks/print-bleed-and-slug-areas.html'],
  pdf: ['Adobe：印刷対応PDFの作成', 'https://helpx.adobe.com/jp/indesign/desktop/print/print-production-and-file-creation/produce-print-ready-pdf-files.html'],
  fonts: ['Adobe：PDFへのフォント埋め込み', 'https://helpx.adobe.com/jp/acrobat/desktop/create-documents/explore-advanced-conversion-settings/font-handling-distiller.html'],
  overprint: ['Adobe：オーバープリント', 'https://helpx.adobe.com/jp/illustrator/using/overprinting.html'],
  paper: ['JAGAT：印刷物と用紙', 'https://www.jagat.or.jp/cat5/dtp/exam/curriculum/printing'],
  paperWeight: ['JAGAT：連量と坪量', 'https://www.jagat.or.jp/story_memo_view.asp?StoryID=6872'],
  halftone: ['JAGAT：網点', 'https://www.jagat.or.jp/cat5/dtp/exam/curriculum/3-3'],
};
