const textbook = 'https://openstax.org/books/principles-economics-3e/pages/';
export const economicsSources = {
  choices: ['OpenStax：予算制約・機会費用・限界的な選択', textbook + '2-1-how-individuals-make-choices-based-on-their-budget-constraint'],
  market: ['OpenStax：需要・供給・市場均衡', textbook + '3-1-demand-supply-and-equilibrium-in-markets-for-goods-and-services'],
  changes: ['OpenStax：需要と供給の変化、価格規制、余剰', textbook + '3-key-concepts-and-summary'],
  elasticity: ['OpenStax：需要と供給の価格弾力性', textbook + '5-1-price-elasticity-of-demand-and-price-elasticity-of-supply'],
  costs: ['OpenStax：短期の固定費用・可変費用・限界費用', textbook + '7-3-costs-in-the-short-run'],
  externalities: ['OpenStax：汚染と負の外部性', textbook + '12-1-the-economics-of-pollution'],
  models: ['OpenStax：理論とモデルによる経済の理解', textbook + '1-3-how-economists-use-theories-and-models-to-understand-economic-issues'],
  publicGoods: ['OpenStax：公共財の性質と供給', textbook + '13-3-public-goods'],
  gdp: ['内閣府：GDPの三面等価（7ページ）', 'https://www.esri.cao.go.jp/jp/esri/about/pdf/gaiyo.pdf'],
  gdpScope: ['米国BEA：GDPが測るものと、その範囲', 'https://www.bea.gov/sites/default/files/methodologies/nipa_primer.pdf'],
  cpi: ['総務省統計局：消費者物価指数の用語', 'https://www.stat.go.jp/data/cpi/yougo.htm'],
  employment: ['総務省統計局：労働力調査の定義と失業率', 'https://www.stat.go.jp/data/roudou/qa-1.htm'],
  money: ['日本銀行：金融政策とは何か', 'https://www.boj.or.jp/about/education/oshiete/seisaku/b26.htm'],
  monetary: ['日本銀行：金融政策が景気・物価に伝わる仕組み', 'https://www.boj.or.jp/about/education/oshiete/seisaku/b28.htm'],
  smith: ['Smith『国富論』（1776初版）：分業と市場', 'https://www.econlib.org/library/Smith/smWN.html?chapter_num=3'],
  ricardo: ['Ricardo『経済学および課税の原理』（1817初版）：外国貿易', 'https://www.econlib.org/library/Ricardo/ricP.html?chapter_num=9'],
  marx: ['Marx『資本論』第1巻（1867）：労働過程と剰余価値', 'https://www.marxists.org/archive/marx/works/1867-c1/ch07.htm'],
  jevons: ['Jevons『経済学の理論』（1871初版）：効用と数学的な分析', 'https://www.econlib.org/library/YPDBooks/Jevons/jvnPE.html?chapter_num=5'],
  marginalHistory: ['Jaffé（1976）：メンガー・ジェヴォンズ・ワルラスの相違', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1465-7295.1976.tb00439.x'],
  marshall: ['Marshall『経済学原理』（1890初版）：需要と供給', 'https://www.econlib.org/library/Marshall/marP.html?chapter_num=31'],
  frisch: ['Frisch（1933）：経済変動とミクロ／マクロの分析（PDF）', 'https://public.econ.duke.edu/~kdh9/Courses/Graduate%20Macro%20History/Readings-1/Frisch_Propagation%20%26%20Impulse.pdf'],
  keynes: ['Keynes『一般理論』（1936）第3章：有効需要', 'https://www.hetwebsite.net/het/texts/keynes/gt/chap03.htm'],
  thrift: ['イングランド銀行（2009）：家計貯蓄と倹約のパラドックス', 'https://www.bankofengland.co.uk/-/media/boe/files/quarterly-bulletin/2009/household-saving'],
  friedman: ['Friedman（1976）：インフレーションと失業（講演PDF）', 'https://www.nobelprize.org/uploads/2018/06/friedman-lecture-1.pdf'],
  macroHistory: ['Mankiw（2006）：ケインズ以後のマクロ経済学の展開', 'https://www.nber.org/papers/w12349'],
  rbc: ['ノーベル賞選考委員会（2004）：キドランドとプレスコットの景気循環研究（PDF）', 'https://www.nobelprize.org/uploads/2018/06/advanced-economicsciences2004.pdf'],
  menuCosts: ['Mankiw（1985）：価格を変える費用と景気変動', 'https://mankiw.scholars.harvard.edu/publications/small-menu-costs-and-large-business-cycles-macroeconomic-model-monopoly'],
  newKeynesian: ['Blanchard・清滝（1985作業論文）：価格設定と需要が生産に及ぼす効果', 'https://www.nber.org/papers/w1770'],
  newSynthesis: ['Goodfriend・King（1997）：新しい新古典派総合と金融政策', 'https://www.richmondfed.org/publications/research/working_papers/1998/wp_98-5'],
  synthesisComment: ['Woodford：新しい新古典派総合が結びつけたもの', 'https://www.richmondfed.org/publications/research/goodfriend/woodford'],
  liquidityTrap: ['Krugman（1998）：日本の不況と流動性の罠', 'https://www.brookings.edu/articles/its-baaack-japans-slump-and-the-return-of-the-liquidity-trap/'],
  reflation: ['岩田規久男（2013）：物価の予想・実質金利と金融緩和の経路', 'https://www.boj.or.jp/about/press/koen_2013/ko130828a.htm'],
  lucas: ['Lucas（1976）：経済政策の計量的評価への批判（PDF）', 'https://people.sabanciuniv.edu/atilgan/FE500_Fall2013/2Nov2013_CevdetAkcay/LucasCritique_1976.pdf'],
  card: ['Card・Krueger：最低賃金と雇用（1993作業論文／1994公刊）', 'https://www.nber.org/papers/w4509'],
  randomization: ['Duflo・Glennerster・Kremer（2006）：経済学研究で無作為化を使う', 'https://www.nber.org/papers/t0333'],
  naturalExperiments: ['ノーベル賞公式解説（2021）：自然実験と因果関係の検証', 'https://www.nobelprize.org/prizes/economic-sciences/2021/popular-information/'],
  simulation: ['日本銀行の研究論文（2024）：Q-JEMによる政策の反実仮想分析', 'https://www.boj.or.jp/research/wps_rev/wps_2024/wp24j22.htm'],
  note: ['蘆澤雄亮：3-07 デザインのミクロとマクロ', 'https://note.com/yashizawa/n/n94d02efaf7ff?magazine_key=m2e7e4bc1b5ae'],
};
