import { LocalPythonCommands } from './LocalPythonCommands.jsx';
import { useState } from 'react';
import { Section, Prompt } from './Common.jsx';
import { designFactors } from './designExamples.js';
import { factorialRows, factorialMainEffect, factorialInteraction, factorialAnova } from './factorialExample.js';
const signed=v=>v>0?`＋${v}`:v<0?`−${Math.abs(v)}`:'0';
const pairs=[[0,1],[0,2],[1,2]];
function MainCalculation(){
 const [column,setColumn]=useState(0),factor=designFactors[column],{groups,difference}=factorialMainEffect(column);
 return <div className="explorer"><div className="segmented" role="group" aria-label="計算する主効果">{designFactors.map((item,i)=><button key={item.name} aria-pressed={column===i} onClick={()=>setColumn(i)}>{item.name}の主効果</button>)}</div><div className="concept-pair design-comparison" aria-live="polite">{groups.map(g=><article key={g.label}><h4>{factor.name}が「{g.label}」</h4><p>条件{g.rows.map(r=>r.condition).join('・')}の12人</p><p>（{g.rows.map(r=>r.average).join(' ＋ ')}）÷ 4<br/>＝ <strong>{g.average}秒</strong></p></article>)}</div><p className="design-reading" aria-live="polite"><strong>「{factor.levels[1]}」−「{factor.levels[0]}」＝ {groups[1].average} − {groups[0].average} ＝ {signed(difference)}秒</strong><br/>ほかの条件を取り混ぜて平均すると、「{factor.levels[1]}」のほうが{Math.abs(difference)}秒速い、という結果です。</p><p>ほかの項目について平均して、一つの項目を変えた違いを見るのが<strong>主効果</strong>です。各条件の人数が同じなので、条件ごとの平均をそのまま平均しています。</p></div>;
}
function InteractionCalculation(){
 const [selected,setSelected]=useState(0),[a,b]=pairs[selected],fa=designFactors[a],fb=designFactors[b],{cells,changes,difference}=factorialInteraction(a,b),sy=v=>240-v*8;
 return <div className="explorer"><div className="segmented" role="group" aria-label="計算する交互作用">{pairs.map(([i,j],index)=><button key={index} aria-pressed={selected===index} onClick={()=>setSelected(index)}>{designFactors[i].name} × {designFactors[j].name}</button>)}</div><p>{fa.name}と{fb.name}の4つの組み合わせに分け、残りの項目について平均します。各マスには6人のデータが入ります。</p><div className="table-scroll"><table className="data-table design-table factorial-interaction"><caption>{fa.name}と{fb.name}の組み合わせ別の平均</caption><thead><tr><th scope="col">{fa.name} ↓<br/>{fb.name} →</th>{fb.levels.map(level=><th scope="col" key={level}>{level}</th>)}</tr></thead><tbody>{cells.map((row,i)=><tr key={i}><th scope="row">{fa.levels[i]}</th>{row.map((cell,j)=><td key={j}>条件{cell.rows.map(r=>r.condition).join('・')}<br/>（{cell.rows.map(r=>r.average).join('＋')}）÷2<br/>＝ <strong>{cell.average}秒</strong></td>)}</tr>)}</tbody></table></div>
 <figure className="factorial-plot"><svg viewBox="0 0 360 300" role="img" aria-label={`${fa.name}別に${fb.name}を変えたときの平均時間。${fa.levels.map((level,i)=>`${level}は${cells[i][0].average}秒から${cells[i][1].average}秒`).join('、')}。`}>{[0,10,20].map(v=><g key={v}><line x1="55" x2="320" y1={sy(v)} y2={sy(v)} stroke="#ddd"/><text x="44" y={sy(v)+6} textAnchor="end">{v}</text></g>)}<text x="55" y="24">平均時間（秒）</text>{cells.map((row,i)=><g key={i}><line x1="90" x2="285" y1={sy(row[0].average)} y2={sy(row[1].average)} stroke={i?'#cc2939':'#111'} strokeWidth="3" strokeDasharray={i?'7 5':undefined}/>{row.map((cell,j)=><circle key={j} cx={90+195*j} cy={sy(cell.average)} r="5" fill={i?'#cc2939':'#111'}/>)}</g>)}{fb.levels.map((level,j)=><text key={level} x={90+195*j} y="269" textAnchor="middle">{level}</text>)}<text x="185" y="295" textAnchor="middle">{fb.name}</text></svg><figcaption><span>黒の実線：{fa.name}「{fa.levels[0]}」</span><span>赤の破線：{fa.name}「{fa.levels[1]}」</span></figcaption></figure>
 <div aria-live="polite"><h4>それぞれ、どれだけ変わった？</h4><p>{fb.name}を「{fb.levels[0]}」から「{fb.levels[1]}」に変えた差を、同じ順に引き算します。</p>{changes.map((change,i)=><p key={i}><strong>{fa.name}が「{fa.levels[i]}」：{cells[i][1].average} − {cells[i][0].average} ＝ {signed(change)}秒</strong><br/>{change===0?'平均時間は変わりません。':`${Math.abs(change)}秒${change<0?'速く':'遅く'}なっています。`}</p>)}<p className="note"><strong>2つの変化を比べる「差の差」</strong><br/>（{signed(changes[1])}）−（{signed(changes[0])}）＝ <strong>{signed(difference)}秒</strong></p><p>{difference===0?'この例では、片方の条件が変わっても、もう片方を変えた差は同じです。線は平行で、この平均値には2項目の交互作用が現れていません。':'片方の条件が変わると、もう片方を変えた差も変わっています。線が平行にならないのは、このためです。これが、このデータに現れた交互作用です。'}</p></div><p className="explainer">ここでは理解のために「差の差」を計算しています。2水準の要因計画で「交互作用効果」として報告する値は、この半分になる表し方もあります。使っている式と引き算の向きを確認します。</p></div>;
}
const python=`import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

df = pd.read_csv("l8-screen-example.csv")
print(df.head())
print(df.groupby(["size", "contrast", "margin"]).time_sec.agg(["count", "mean", "std"]))
# C(...) は、1・2を数の大小ではなくカテゴリーとして扱う指定。
# * は、主効果とすべての交互作用を含める指定。
model = ols("time_sec ~ C(size) * C(contrast) * C(margin)", data=df).fit()
print(sm.stats.anova_lm(model, typ=2))`;
export function FactorialWorkedExample(){return <Section id="factorial-calculation" title="実測値から、主効果・交互作用を計算する">
 <p>ここからは、<strong>別の架空データを使ったL8の計算練習</strong>です。サイズ・コントラスト・余白を全8通りに組み合わせ、別々の3人ずつ、合計24人に試してもらったとします。先ほどのL4の行平均とは異なるデータです。</p>
 <h3>1．一人ずつ記録し、条件ごとの平均を出す</h3><p>表計算ソフトには、<strong>1行に1人分、列に「参加者ID・条件・サイズ・コントラスト・余白・時間」</strong>を記録します。下の表は見やすいように、同じ条件の3人をまとめています。平均だけを残さず、一人ずつの値を保存してください。</p>
 <div className="table-scroll"><table className="data-table design-table factorial-raw"><caption>8条件 × 別々の3人＝24人の測定値</caption><thead><tr><th scope="col">条件</th><th scope="col">サイズ・コントラスト・余白</th><th scope="col">3人の時間<br/>（秒）</th><th scope="col">平均<br/>（秒）</th></tr></thead><tbody>{factorialRows.map(row=><tr key={row.condition}><th scope="row">{row.condition}</th><td>{row.levels.map((level,i)=>designFactors[i].levels[level-1]).join('・')}</td><td>{row.values.join('・')}</td><td>{row.average}</td></tr>)}</tbody></table></div>
 <p>条件1なら、<strong>（22 ＋ 24 ＋ 26）÷ 3＝24秒</strong>。ほかの条件も同じように平均します。3人は計算練習の人数であり、研究に十分な人数という意味ではありません。</p><p><a href={`${import.meta.env.BASE_URL}data/l8-screen-example.csv`} download>24人分の生データをCSVでダウンロード ↓</a></p><p className="small-note">CSVのsize・contrast・marginは、1＝小・低・狭い、2＝大・高・広いです。time_secが秒単位の時間です。</p>
 <h3>2．主効果：一つの項目で分けて、平均を引き算する</h3><p>サイズなら「小の条件」と「大の条件」をまとめます。どちらにも、コントラストと余白の全組み合わせが入っています。</p><MainCalculation/>
 <h3>3．交互作用：条件ごとに、変化のしかたを比べる</h3><p>コントラストを低から高にするとき、小さいボタンでも大きいボタンでも、同じだけ速くなるでしょうか。</p><InteractionCalculation/>
 <h3>4．ばらつきと比べて、F値・p値を読む</h3><p>「測定のばらつきに比べても大きい差か」は、02の分散分析につながります。今回は3項目の主効果とすべての交互作用を入れた、三元配置分散分析です。</p>
 <ol className="action-steps"><li><strong>同じ条件の中のばらつきを計算する。</strong><p>条件1の平均は24秒。平均との差を二乗して足すと、<br/>（22−24）² ＋（24−24）² ＋（26−24）² ＝ <strong>8</strong>。</p><p>この練習データは、どの条件もこの値が8です。8条件を足すと、誤差の平方和は<strong>8 × 8＝64</strong>です。</p></li><li><strong>誤差の平方和を、自由度で割る。</strong><p>各条件で3人から平均を1つ求めたので、自由度は3−1＝2。8条件で<strong>8 × 2＝16</strong>です。誤差の平均平方は<strong>64 ÷ 16＝4</strong>です。</p></li><li><strong>各効果も平方和にし、誤差と比べる。</strong><p>今回のように「各条件が同人数・各項目が2水準・全8通り」の計画では、サイズの主効果の平方和は<strong>24人 ×（−6）² ÷ 4＝216</strong>。</p><p>サイズ × コントラストは差の差が12秒なので、平方和は<strong>24人 × 12² ÷ 16＝216</strong>です。</p><p>ここでは各効果の自由度が1なので、平均平方も216。誤差の平均平方4で割り、どちらも<strong>F＝216 ÷ 4＝54</strong>になります。</p></li></ol>
 <p>Fと自由度からp値を計算する部分は、解析ソフトに任せられます。今回は各効果の自由度1・誤差の自由度16のF分布を使います。</p>
 <div className="table-scroll"><table className="data-table design-table factorial-anova"><caption>24人の生データから計算した三元配置分散分析</caption><thead><tr><th scope="col">調べるもの</th><th scope="col">平方和</th><th scope="col">自由度</th><th scope="col">平均平方</th><th scope="col">F値</th><th scope="col">p値</th></tr></thead><tbody>{factorialAnova.terms.map(t=><tr key={t.label}><th scope="row">{t.label}</th><td>{t.ss}</td><td>{t.df}</td><td>{t.ms}</td><td>{t.f}</td><td>{t.p<.001?'＜0.001':t.p.toFixed(3)}</td></tr>)}<tr><th scope="row">誤差</th><td>64</td><td>16</td><td>4</td><td>—</td><td>—</td></tr><tr><th scope="row">全体</th><td>{factorialAnova.totalSS}</td><td>23</td><td>—</td><td>—</td><td>—</td></tr></tbody></table></div>
 <p><strong>サイズ × コントラストはF＝54、p＜0.001。</strong>今回のモデルの前提のもとでは、「交互作用がない」だけでは説明しにくい結果です。主効果だけで「高コントラストならいつでも速い」とまとめず、組み合わせ別の平均に戻ります。p値が1の行も、「交互作用が絶対にない」と証明したわけではありません。</p><p className="note">実際には、観測が独立か、条件内のばらつきを共通とみなせるか、残差が正規分布から大きく外れていないかを、設計と図で確かめます。同じ人を繰り返し測った場合や人数が不ぞろいな場合に、この計算をそのまま当てはめません。</p>
 <h3>5．結果から、次に何をするか決める</h3><p className="note"><strong>考察の書き方の例</strong><br/>平均すると、大きいボタンは小さいボタンより6秒速かった。一方、コントラストを高くすると、小さいボタンでは8秒速くなったが、大きいボタンでは4秒遅くなった。このため、サイズとコントラストは組み合わせて検討する。今回もっとも短かった「大・低・広い」は平均8秒だった。これを候補にし、比較する画面をあらかじめ決めたうえで、別の参加者でも時間と誤操作を確認する。</p>
 <h3>Pythonで同じ計算をするなら</h3><p>CSVを作業用フォルダーに保存し、下の例を自分のPCのPythonで実行すると、人数・平均・標準偏差と分散分析表が出ます。コードはAIに作ってもらって構いません。<strong>自分で指定するのは、何を測ったか、各列の意味、同じ人を繰り返し測ったか、何を比較したいか</strong>です。</p><details><summary>確認用のPythonコード</summary><LocalPythonCommands packages="pandas statsmodels" filename="factorial_analysis.py"/><p>次のコードをCSVと同じフォルダーに保存します。</p><pre className="code-block"><code>{python}</code></pre></details><Prompt text={'自分のPCのl8-screen-example.csvを読み込むPythonコードを作ってください。コードはCSVと同じフォルダーにfactorial_analysis.pyとして保存します。必要なライブラリの準備と実行の命令も示してください。別々の24人が8条件のいずれか一つを試し、各条件3人です。participant_idは参加者ID、size・contrast・marginは1/2のカテゴリー、time_secは操作時間（秒）です。目的は、3項目の主効果と交互作用を調べることです。最初に行数・型・欠測・ID重複と各条件の人数を確認し、条件別の平均・標準偏差、主効果図、交互作用図を出してください。3つの主効果と全交互作用を含む三元配置分散分析と残差の確認を行い、平方和・自由度・F値・p値を出してください。除外や変換を自動でせず、前提を満たすかを説明し、平均差と組み合わせ別の結果から言えることを整理してください。コードは処理のまとまりごとに説明し、出力の意味を説明してください。'}/>
 <p>自分のデータでも、<strong>生データを保存 → 条件ごとに図と平均 → 主効果 → 交互作用 → 設計に合う解析 → 組み合わせ別の考察</strong>の順で進めます。</p>
 </Section>;}
