// Publication years refer to the original work, not the linked reprint or translation.
const principlesSource = (chapter, path, reading) => ({
  author: 'David S. Bright／Anastasia H. Cortes ほか', year: '2019',
  title: `Principles of Management — ${chapter}`,
  publication: 'Rice University / OpenStax. 2019年3月20日刊。オンライン教科書。',
  url: `https://openstax.org/books/principles-management/pages/${path}`,
  access: 'OpenStaxの教科書本文（無料公開）',
  person: '戦略、組織、人材、意思決定、計画と統制など、マネジメントの主要領域を扱う入門教科書。',
  reading,
});

export const managementSources = {
  openstax_principles: principlesSource('Preface', 'preface', '計画・組織化・リーダーシップ・統制を土台に、主要領域と現代的な課題をどう配置しているか確認する。'),
  openstax_strategy: principlesSource('9. The Strategic Management Process', '9-introduction', '目的やビジョン、戦略目標、計画と評価のつながりを読む。'),
  openstax_decisions: principlesSource('2. Managerial Decision-Making', '2-introduction', '判断の種類、認知の偏り、個人と集団の意思決定の違いを読む。'),
  openstax_people: principlesSource('11. Human Resource Management', '11-introduction', '人材の採用、評価、報酬、育成の関係を読む。'),
  openstax_leadership: principlesSource('13. Leadership', '13-introduction', 'リーダーシップの特性・行動・状況に注目する研究の違いを読む。'),
  openstax_control: principlesSource('17. Organizational Planning and Controlling', '17-introduction', '計画、統制、目標管理と、従業員の参加との関係を読む。'),
  openstax_innovation: principlesSource('18. Management of Technology and Innovation', '18-introduction', '新しい技術や知識を組織の内外で生み、取り入れる過程を読む。'),
  openstax_change: principlesSource('10.2 Organizational Change', '10-2-organizational-change', '構造・技術・文化の変化を区別し、それらの相互関係を読む。'),
  oxford_manage: {
    author: 'Oxford University Press', year: '年記なし', title: 'manage — Oxford Advanced Learner’s Dictionary',
    publication: 'オンライン辞書。2026年9月14日参照。',
    url: 'https://www.oxfordlearnersdictionaries.com/us/definition/english/manage', access: '現代の語義・Word Origin（語源）',
    person: '語源と現在の用法を確認するための辞書項目。',
    reading: 'Word Originと、business/team、money/time/informationの語義を読み、語の出発点と現在の使われ方を区別する。',
  },
  etym_management: {
    author: 'Douglas Harper', year: '年記なし', title: 'management — Online Etymology Dictionary',
    publication: 'オンライン語源辞典。2026年9月14日参照。',
    url: 'https://www.etymonline.com/word/management', access: 'managementの語源と関連するmanageの項目',
    person: 'managementという語の成立と意味の広がりを確認するための語源辞典。',
    reading: 'manage ＋ -mentという成り立ちと、行為を表す意味から経営陣を指す意味への広がりを確認する。',
  },
  openstax_organization: {
    author: 'OpenStax', year: '2019', title: 'Organizational Behavior, 1.3 The Nature of Management',
    publication: 'Rice University / OpenStax. オンライン教科書。',
    url: 'https://openstax.org/books/organizational-behavior/pages/1-3-the-nature-of-management', access: '教科書本文',
    person: '組織行動論の入門教科書。組織におけるマネジメントの役割を整理する。',
    reading: 'What Is Management?の定義と、企業以外の組織にも管理の仕事があるという説明を読む。',
  },
  openstax_management: {
    author: 'Gitmanほか／OpenStax', year: '2026', title: 'Introduction to Business 2e, 6.1 The Role of Management',
    publication: 'Rice University / OpenStax. 第2版、2026年4月22日刊。',
    url: 'https://openstax.org/books/introduction-business-2e/pages/6-1-the-role-of-management', access: '教科書本文',
    person: 'マネジメントの四つの機能と、効率・有効性の区別を説明する入門教科書。',
    reading: '四つの機能の相互関係と、efficiencyとeffectivenessの定義を読む。',
  },
  mintzberg_interview: {
    author: 'ヘンリー・ミンツバーグ', year: '2009', title: 'What Managers Really Do',
    publication: 'The Wall Street Journal, August 17. Martha E. Mangelsdorfによるインタビュー。',
    url: 'https://mintzberg.org/sites/default/files/article/download/mgrsreallydo.pdf', access: '著者公開のインタビュー本文（PDF）',
    person: 'Managing刊行時に、著者自身が観察の結果と三つの働きかけを説明したインタビュー。',
    reading: '2ページ目のinformation、people、actionの区別を読み、数値目標だけで仕事を動かそうとすることへの批判を確かめる。',
  },
  drucker: {
    author: 'ピーター・F・ドラッカー', year: '1954', title: 'The Practice of Management',
    publication: 'Harper & Brothers. 邦題：現代の経営。リンクは後年の再刊版。',
    url: 'https://www.routledge.com/The-Practice-of-Management/Drucker/p/book/9780750685047', access: '出版社の紹介・目次',
    person: '企業や組織の実践を通じて、マネジメントの仕事と責任を論じた著述家。',
    reading: '第1〜3章のマネジメントの役割と、第11章の目標と自己統制を読む。目標を上から課すことと、本人が成果への貢献を考えることを比較する。',
  },
  mintzberg: {
    author: 'ヘンリー・ミンツバーグ', year: '2009', title: 'Managing', publication: 'Berrett-Koehler / Pearson.',
    url: 'https://mintzberg.org/books/managing', access: '著者による紹介・調査付録への入口',
    person: 'マネジャーの実際の仕事を観察し、組織と経営を研究してきた研究者。',
    reading: '29人のマネジャーの一日を扱う付録に注目する。「計画する人」というイメージに収まらない活動を探す。',
  },
  taylor: {
    author: 'フレデリック・W・テイラー', year: '1911', title: 'The Principles of Scientific Management', publication: 'Harper & Brothers. 邦題：科学的管理法。',
    url: 'https://www.gutenberg.org/cache/epub/6435/pg6435-images.html', access: '原著全文（英語）',
    person: '工場の作業方法を分析し、科学的管理を提案した米国の技術者。',
    reading: 'Chapter I の出来高単価の切下げとsystematic soldiering（組織的な生産制限）、Chapter II のtraditional knowledge（伝統的な作業知識）を規則や公式に整理する記述を読む。課業と報酬の設計が、これらの問題にどう答えようとしたかを確かめる。',
  },
  taylor_shop: {
    author: 'フレデリック・W・テイラー', year: '1903', title: 'Shop Management',
    publication: '1903年にASMEで発表。リンクは1911年の再刊版。本文に1895年の論文 A Piece Rate System の引用を含む。',
    url: 'https://www.gutenberg.org/cache/epub/6464/pg6464.html', access: '原著全文（英語）',
    person: '科学的管理法に先立ち、課業、賃金、工場管理の仕組みを論じたテイラーの著作。',
    reading: 'A Piece Rate Systemを引用する箇所の、1日10個・一個35セントと、10個未満・一個25セントの事例を読む。高賃金と単位当たりの低い労務費を、どう両立させようとしたかを確かめる。',
  },
  fayol: {
    author: 'アンリ・ファヨール', year: '1916', title: 'Administration industrielle et générale',
    publication: 'フランス語で初出。Constance Storrsによる英訳 General and Industrial Management は1949年。',
    url: 'https://books.google.com/books?id=WFp5DQAAQBAJ', access: '再刊版の書誌・紹介・限定プレビュー',
    person: '鉱山企業を経営した経験から、組織全体を管理する機能を整理した実務家。',
    reading: '予測・計画、組織、指揮、調整、統制という機能と、技術的な仕事との違いを読む。引用する際は利用した版のページを確認する。',
  },
  weber: {
    author: 'マックス・ウェーバー', year: '1921–1922', title: 'Wirtschaft und Gesellschaft（経済と社会）',
    publication: '死後に編纂・刊行。版によって構成が異なる。リンクは官僚制に関する英訳抜粋。',
    url: 'https://open.oregonstate.education/sociologicaltheory/chapter/bureaucracy/', access: '原典の英訳抜粋・大学教材',
    person: '社会的な行為や支配の仕組みを研究した社会学者。',
    reading: '官職の権限、職務の範囲、記録、専門的な訓練がどう結びついているかを読む。日常語の「お役所仕事」と同一視しない。',
  },
  hawthorne: {
    author: 'Harvard Business School, Baker Library', year: '研究期間 1924–1933', title: 'The Human Relations Movement: Harvard Business School and the Hawthorne Experiments',
    publication: 'ホーソン研究の史料展示。年は研究が行われた期間で、ウェブ展示の刊行年ではない。',
    url: 'https://www.library.hbs.edu/hc/hawthorne/intro.html', access: '史料所蔵機関による展示・解説',
    person: 'エルトン・メイヨー、フリッツ・レスリスバーガーらが関わった研究を、記録や写真からたどれる。',
    reading: '照明実験、面接、集団の研究を区別して読む。「注目されたから生産性が上がった」という一文で全研究を説明できるか考える。',
  },
  barnard: {
    author: 'チェスター・I・バーナード', year: '1938', title: 'The Functions of the Executive',
    publication: 'Harvard University Press. 邦題：経営者の役割。',
    url: 'https://books.google.com/books?id=K4xEAAAAIAAJ', access: '初版の書誌・限定プレビュー',
    person: '企業の経営経験をもとに、組織を協働の体系として論じた実務家。',
    reading: '共通の目的、協働への意欲、コミュニケーションという成立条件に注目する。「組織の目的」と参加者自身の動機を分けて読む。',
  },
  mcgregor: {
    author: 'ダグラス・マグレガー', year: '1960', title: 'The Human Side of Enterprise',
    publication: 'McGraw-Hill. リンクは注釈付き再刊版。',
    url: 'https://www.mheducation.com/highered/mhp/product/human-side-enterprise-annotated-edition.html', access: '出版社の紹介・目次',
    person: '働く人に対する管理者の前提を、組織運営の問題として論じた研究者。',
    reading: 'X理論・Y理論が「人の性格の分類」なのか、「管理者の置く前提」なのかを確かめる。',
  },
  simon: {
    author: 'ハーバート・A・サイモン', year: '1947', title: 'Administrative Behavior',
    publication: 'Macmillan. 邦題：経営行動。リンクは本人による1978年のノーベル賞講演。',
    url: 'https://www.nobelprize.org/uploads/2018/06/simon-lecture.pdf', access: '著者による後年の講演本文',
    person: '行政、組織、心理、情報処理にまたがって、人の意思決定を研究した研究者。',
    reading: '講演 Rational Decision-Making in Business Organizations の bounded rationality を読む。選択肢、情報、計算能力の制約を探す。',
  },
  chandler: {
    author: 'アルフレッド・D・チャンドラー・ジュニア', year: '1962', title: 'Strategy and Structure: Chapters in the History of the American Industrial Enterprise',
    publication: 'MIT Press. リンク先のペーパーバックは1969年、初版ハードカバーは1962年。',
    url: 'https://mitpress.mit.edu/9780262530095/strategy-and-structure/', access: '出版社の紹介・版情報',
    person: '米国企業の成長と管理組織の変化を歴史的に研究した経営史家。',
    reading: 'デュポン、GMなどの事例で、事業の拡張と分権的な組織構造がどう関係したかを読む。',
  },
  lawrence: {
    author: 'ポール・R・ローレンス／ジェイ・W・ローシュ', year: '1967', title: 'Differentiation and Integration in Complex Organizations',
    publication: 'Administrative Science Quarterly, 12(1), 1–47. DOI: 10.2307/2391211.',
    url: 'https://doi.org/10.2307/2391211', access: '原論文・抄録（本文は利用条件による）',
    person: '部門ごとの環境と、組織内部の分化・統合を比較研究した研究者。',
    reading: '分化と統合を対義語として終わらせず、なぜ両方が必要なのかを読む。6組織を比較した研究の範囲にも注意する。',
  },
  senge: {
    author: 'ピーター・M・センゲ', year: '1990', title: 'The Fifth Discipline: The Art and Practice of the Learning Organization',
    publication: 'Doubleday/Currency. 邦題：学習する組織。リンクは2006年の改訂版。',
    url: 'https://penguinrandomhousesecondaryeducation.com/book/?isbn=9780385517256', access: '出版社の紹介・目次・抜粋',
    person: 'システム思考を軸に、組織が学び続けるための実践を整理した研究者・著述家。',
    reading: '五つのディシプリンと、その関係を読む。とくに、自分たちの問題の捉え方そのものを見直す場面に注目する。',
  },
  nonaka: {
    author: '野中郁次郎', year: '1994', title: 'A Dynamic Theory of Organizational Knowledge Creation',
    publication: 'Organization Science, 5(1), 14–37. DOI: 10.1287/orsc.5.1.14.',
    url: 'https://www.lamsade.dauphine.fr/~giard/Organization_Science_Nonaka94.pdf', access: '原論文本文（大学公開PDF）',
    person: '個人の知識と組織の知識創造の関係を研究した経営学者。',
    reading: '暗黙知・形式知と、四つの知識変換を読む。文書を保存することと、新しい知識を生むことの違いを考える。',
  },
  ryan: {
    author: 'リチャード・M・ライアン／エドワード・L・デシ', year: '2000', title: 'Intrinsic and Extrinsic Motivations: Classic Definitions and New Directions',
    publication: 'Contemporary Educational Psychology, 25(1), 54–67. DOI: 10.1006/ceps.1999.1020.',
    url: 'https://www.selfdeterminationtheory.org/SDT/documents/2000_RyanDeci_IntExtDefs.pdf', access: '原論文本文（著者側公開PDF）',
    person: '自己決定理論を発展させ、動機づけと基本的心理欲求を研究した心理学者。',
    reading: '内発的動機づけと、外発的動機づけの内在化を区別する。自律性・有能感・関係性を、自分の経験に照らして読む。',
  },
  gagne: {
    author: 'マリーズ・ガニェ／エドワード・L・デシ', year: '2005', title: 'Self-determination theory and work motivation',
    publication: 'Journal of Organizational Behavior, 26, 331–362. DOI: 10.1002/job.322.',
    url: 'https://www.selfdeterminationtheory.org/SDT/documents/2005_GagneDeci_JOB_SDTtheory.pdf', access: '原論文本文（著者側公開PDF）',
    person: '自己決定理論を仕事の動機づけへ接続した研究者。',
    reading: 'autonomous motivation と controlled motivation の区別を、報酬制度や仕事の設計に結びつけて読む。',
  },
  pink: {
    author: 'ダニエル・H・ピンク', year: '2009', title: 'Drive: The Surprising Truth About What Motivates Us',
    publication: 'Riverhead Books. 邦題：モチベーション3.0。',
    url: 'https://www.danpink.com/books/drive/', access: '著者による内容紹介',
    person: '心理学などの研究を、働き方や日常の言葉へ翻訳する一般向け著述家。',
    reading: '自律性・熟達・目的という整理を読む。紹介される実験の条件は、参考文献から研究そのものに戻って確かめる。',
  },
  edmondson: {
    author: 'エイミー・エドモンドソン', year: '1999', title: 'Psychological Safety and Learning Behavior in Work Teams',
    publication: 'Administrative Science Quarterly, 44(2), 350–383. DOI: 10.2307/2666999.',
    url: 'https://web.mit.edu/curhan/www/docs/Articles/15341_Readings/Organizational_Learning_and_Change/Edmondson_1999_Psychological_safety.pdf', access: '原論文本文（大学公開PDF）',
    person: 'チームにおける対人関係上のリスクと、学習行動を研究する研究者。',
    reading: '心理的安全性の定義と、製造企業の51チームという調査対象を確認する。学習行動との関係から、どこまで結論を述べられるかを読む。',
  },
  laloux: {
    author: 'フレデリック・ラルー', year: '2014', title: 'Reinventing Organizations',
    publication: 'Nelson Parker. 日本語版：ティール組織（鈴木立哉訳、嘉村賢州解説、英治出版、2018）。',
    url: 'https://eijipress.co.jp/en/products/2226', access: '日本語版出版社の紹介・目次・試し読みへの入口',
    person: '組織変革の実務を経験し、先駆的な組織の事例から新しい組織像を提案した著述家。',
    reading: '第II部の自主経営・全体性・存在目的を読む。色による発達段階のモデルと、各組織の具体的な運営方法を分けて検討する。',
  },
  lee: {
    author: 'マイケル・Y・リー／エイミー・C・エドモンドソン', year: '2017', title: 'Self-managing organizations: Exploring the limits of less-hierarchical organizing',
    publication: 'Research in Organizational Behavior, 37, 35–58. DOI: 10.1016/j.riob.2017.10.002.',
    url: 'https://www.sciencedirect.com/science/article/pii/S0191308517300059', access: '原論文・抄録・公開範囲の本文',
    person: '自己管理型組織を既存研究の中に位置づけ、その可能性と限界を検討した研究者。',
    reading: '自己管理型組織の定義を読む。一部のチームへの権限委譲と、組織全体の権限構造を変えることの違いを考える。',
  },
  hamel: {
    author: 'ゲイリー・ハメル／ミケーレ・ザニーニ', year: '2020', title: 'Humanocracy: Creating Organizations as Amazing as the People Inside Them',
    publication: 'Harvard Business Review Press. 日本語版：ヒューマノクラシー（東方雅美訳、英治出版、2023）。',
    url: 'https://www.humanocracy.com/sites/default/files/2020-08/Humanocracy-preface-ch1.pdf', access: '著者公開の序文・第1章',
    person: '経営思想・戦略を研究するハメルと、組織変革に携わるザニーニによる共著。',
    reading: '序文と第1章から、官僚制のどの特徴を問題にしているかを読む。事例の成果と、その原因についての著者の解釈を区別する。',
  },
  freeman: {
    author: 'R・エドワード・フリーマン', year: '1984', title: 'Strategic Management: A Stakeholder Approach',
    publication: 'Pitman. リンクはCambridge University Pressによる2010年の再刊版。',
    url: 'https://www.cambridge.org/core/books/strategic-management/E3CC2E2CE01497062D7603B7A8B9337F', access: '出版社の紹介・目次',
    person: '企業活動と、その活動に関わる人々の利益・倫理を結びつけて論じた研究者。',
    reading: 'Part I のステークホルダー概念と管理の考え方を読む。関係者を列挙した後、利害が衝突するときの判断へ進む。',
  },
};
