// The groups organize selected publications; they do not imply that schools replaced one another.
export const managementEpochs = [
  {
    id: 'classical', years: '1911–1922', title: '個人の腕に頼る仕事を、組織の仕組みにする',
    context: '仕事の知識や権限が個人に依存したままでは、大きな組織の仕事を安定させにくい。',
    shift: '作業・報酬・役割・権限を、分析して設計できるものとして捉える。',
    works: [
      { id: 'taylor', name: 'テイラー', title: '科学的管理法',
        why: '作業の勘所は職人が握り、管理側は適切な方法・時間を把握しにくい。単価切下げも、生産を抑える理由になっていた。',
        points: ['経験知を明示する：勘・コツを手順と標準時間へ。', '数値で統制する：課業・作業時間・賃金を結びつける。'],
        strand: 'work', paragraphs: [0, 1, 2, 3], reading: ['taylor', 'taylor_shop'] },
      { id: 'fayol', name: 'ファヨール', title: 'Administration industrielle et générale',
        why: '個々の作業を改善しても、全体の計画・分担・調整がなければ組織は動かない。',
        points: ['管理そのものを、学び教えられる仕事にする。', '計画・組織・指揮・調整・統制の機能を整理する。'],
        strand: 'work', paragraphs: [0] },
      { id: 'weber', name: 'ウェーバー', title: '経済と社会',
        why: '個人への忠誠や人柄に頼る権限では、担当者の交代や恣意によって判断が揺らぐ。',
        points: ['人と役職を分け、権限を規則と職務に結びつける。', '専門性・文書記録・階層による官僚制を分析する。'],
        strand: 'decision', paragraphs: [0, 1] },
    ],
  },
  {
    id: 'cooperation', years: '1924–1938', title: '仕組みに加え、人が協力する条件を見る',
    context: '設備・手順・組織図を整えるだけでは、実際の働き方や協力を説明しきれない。',
    shift: '人間関係、集団の規範、参加する人の動機を、組織の問題として扱う。',
    works: [
      { id: 'hawthorne', name: 'メイヨー、レスリスバーガーら', title: 'ホーソン研究',
        why: '生産性と働く人の経験を理解するため、作業条件だけでなく職場の関係を調べる必要があった。',
        points: ['人を、集団や人間関係の中で捉える。', '公式の手順に表れない規範や感情にも目を向ける。'],
        strand: 'people', paragraphs: [0, 2] },
      { id: 'barnard', name: 'バーナード', title: '経営者の役割',
        why: '人々の参加理由は同じではなく、命令や組織図だけでは協力が続かない。',
        points: ['組織を、協働が成り立つ仕組みとして捉える。', '共通目的・協働意欲・意思疎通を成立条件に置く。'],
        strand: 'people', paragraphs: [0] },
    ],
  },
  {
    id: 'decisions', years: '1947–1954', title: '命令の遂行から、判断と成果へ目を向ける',
    context: '仕事を進めるには、不完全な情報で選択し、何を成果とするかを定める必要がある。',
    shift: '組織を意思決定の場として捉え、目的と一人ひとりの貢献をつなぐ。',
    works: [
      { id: 'simon', name: 'サイモン', title: '経営行動',
        why: '情報・時間・能力には限りがあり、すべての選択肢を比較して最適を選ぶことはできない。',
        points: ['限定合理性：人が実際に判断できる範囲から考える。', '満足化：要求を満たす案を探索する過程を捉える。'],
        strand: 'decision', paragraphs: [0, 1] },
      { id: 'drucker', name: 'ドラッカー', title: '現代の経営',
        why: '個々の仕事を効率化しても、事業の目的が曖昧では何を成果とするか判断できない。',
        points: ['事業の目的から、各人の仕事と貢献を考える。', '目標を共有し、本人が自分の仕事を統制する。'],
        strand: 'decision', paragraphs: [0, 1] },
    ],
  },
  {
    id: 'contingency', years: '1960–1967', title: 'どこでも同じ管理が通用するのかを問う',
    context: '人間観、事業の範囲、部門の環境が違えば、必要な関わり方や組織構造も変わる。',
    shift: '管理の仕方を、その前提と、成り立つ条件から検討する。',
    works: [
      { id: 'mcgregor', name: 'マグレガー', title: 'The Human Side of Enterprise',
        why: '「人は放っておくと怠ける」という管理者の前提が、強い監督や統制を生んでいる。',
        points: ['X理論・Y理論：管理者の人間観を問い直す。', '自己統制や責任を発揮できる条件を考える。'],
        strand: 'people', paragraphs: [0, 1] },
      { id: 'chandler', name: 'チャンドラー', title: 'Strategy and Structure',
        why: '事業が多角化・広域化すると、従来の管理組織では調整しきれなくなる。',
        points: ['組織構造を、事業の戦略との関係で見る。', '米国企業の歴史から、事業拡張と分権化を検討する。'],
        strand: 'decision', paragraphs: [0, 1] },
      { id: 'lawrence', name: 'ローレンス＆ローシュ', title: '複雑な組織における分化と統合〔論文〕',
        why: '研究・営業・生産では、必要な情報や時間の感覚が異なり、一律の管理では噛み合わない。',
        points: ['分化：部門がそれぞれの環境に対応する。', '統合：異なる専門性を、全体の仕事へつなぐ。'],
        strand: 'decision', paragraphs: [0, 1, 2] },
    ],
  },
  {
    id: 'stakeholders', years: '1984', title: '成果を、組織の外の関係者からも問う',
    context: '企業の活動は、顧客・従業員・取引先・地域社会などの利害と結びついている。',
    shift: '誰に価値を生み、誰に影響するかを、戦略と責任の問題に含める。',
    works: [
      { id: 'freeman', name: 'フリーマン', title: 'Strategic Management: A Stakeholder Approach',
        why: '企業の戦略を考えるには、株主を含む多様な関係者の利害と影響を捉える必要がある。',
        points: ['企業を、ステークホルダーとの関係から捉える。', '関係者にとっての価値を、戦略の問いに組み込む。'],
        strand: 'decision', paragraphs: [0, 2] },
    ],
  },
  {
    id: 'learning', years: '1990–1999', title: '既存の仕事を回すことから、知を生むことへ',
    context: '今ある手順や知識の活用だけでは、新しい問題や、繰り返す失敗に対応しきれない。',
    shift: '経験から学び、知識を生み、考え方自体を更新する過程を扱う。',
    works: [
      { id: 'senge', name: 'センゲ', title: '学習する組織',
        why: '目の前の問題への対処が、別の問題や同じ失敗を生むことがある。',
        points: ['システム思考：出来事の循環やつながりを見る。', '組織として、行動を生む前提や見方を学び直す。'],
        strand: 'work', paragraphs: [0, 2] },
      { id: 'nonaka', name: '野中郁次郎', title: '組織的知識創造の動態理論〔論文〕',
        why: '情報処理だけを見ても、個人の経験から組織の新しい知が生まれる過程を説明できない。',
        points: ['暗黙知と形式知の相互作用から、知識創造を捉える。', '個人の知を、対話や実践を通じて組織へ広げる。'],
        strand: 'work', paragraphs: [0, 1, 2] },
      { id: 'edmondson', name: 'エドモンドソン', title: '心理的安全性とチームの学習行動〔論文〕',
        why: '質問や失敗の報告には、無能に見られたり、責められたりする対人リスクが伴う。',
        points: ['心理的安全性：対人リスクを取れるという共有認識。', 'その認識と、チームの学習行動の関連を調べる。'],
        strand: 'people', paragraphs: [0, 2] },
    ],
  },
  {
    id: 'autonomy', years: '2000–2020', title: '自律的に働く条件と、権限の置き方を問う',
    context: '意欲や創造性を支えるには、外からの働きかけに加え、本人の納得や判断の余地を見る必要がある。',
    shift: '動機づけの質を研究する議論と、組織の権限を分散する提案が展開する。',
    works: [
      { id: 'ryan', name: 'ライアン＆デシ', title: '内発的・外発的動機づけの整理〔論文〕',
        why: '同じ行動でも、罰を避けるためか、本人が価値を認めているかで、動機の質が違う。',
        points: ['動機づけを、強さに加えて自律性から捉える。', '自律性・有能感・関係性を支える条件を考える。'],
        strand: 'people', paragraphs: [0, 1] },
      { id: 'pink', name: 'ダニエル・ピンク', title: 'Drive／モチベーション3.0',
        why: '報酬を増やせば意欲も成果も上がる、という実務の前提を問い直す必要がある。',
        points: ['自律性・熟達・目的から、仕事の設計を考える。', '動機づけ研究を、一般読者と実務へ伝える。'],
        strand: 'people', paragraphs: [0, 2] },
      { id: 'laloux', name: 'ラルー', title: 'Reinventing Organizations／ティール組織',
        why: '細かな指示や職場の役割の枠が、人の主体性や持ち味を制約する。',
        points: ['自主経営・全体性・存在目的という組織像を提案する。', '事例を通じて、権限と責任を分散する運営を考える。'],
        strand: 'decision', paragraphs: [0, 1, 3] },
      { id: 'hamel', name: 'ハメル＆ザニーニ', title: 'Humanocracy／ヒューマノクラシー',
        why: '承認の階層が増えると、現場の知恵が判断に届かず、工夫や実験が遅れる。',
        points: ['人の能力を阻む、官僚制の仕組みを問い直す。', '現場の裁量・情報の公開・小さな実験を支える。'],
        strand: 'decision', paragraphs: [0, 1, 2] },
    ],
  },
];

export const managementStrands = {
  work: { label: '仕事・知識', color: '#236963', question: '仕事と知識を、どう扱うか。', change: '経験を手順にすることから、新しい知を生む過程へ。' },
  people: { label: '人間・協働', color: '#ab3545', question: '人は、なぜ協力するのか。', change: '報酬に加えて、人間関係や本人の納得にも目を向ける。' },
  decision: { label: '判断・責任', color: '#69539a', question: '誰が決め、責任を負うのか。', change: '判断の限界、環境との関係、権限の分散を考える。' },
};
