import PageLink from './PageLink.jsx';
import { TsneConcept, TsnePlots } from './TsneLesson.jsx';
import { LocalPythonCommands } from './LocalPythonCommands.jsx';
import { Section, Prompt } from './Common.jsx';
import { AnalysisOutputReading, EigenvalueExplanation, PcaAxisChoice, outputGuideRows } from './AnalysisOutputReading.jsx';
import { CategoryPatternPlots } from './CategoryPatternPlots.jsx';
import { MethodCoordinatePlot } from './MethodCoordinatePlot.jsx';
import { methodGuides } from './methodGuides.js';
import exampleData from './methodExampleResults.json';
const base=import.meta.env.BASE_URL;
function valueText(value,column=''){
 if(value===null||value==='-')return '—';
 if(typeof value==='boolean')return column==='reject'?(value?'棄却':'棄却しない'):(value?'はい':'いいえ');
 if(typeof value!=='number')return value;
 if(/(^p$|^p-|_p$|p-value|PR\(>F\)|両側p|カイ二乗p|Fisher両側p)/.test(column)&&value<.0001)return '＜0.0001';
 if(Math.abs(value)<1e-12)return '0';
 if(value!==0&&Math.abs(value)<.0001)return value.toExponential(2);
 return Number.isInteger(value)?value:value.toFixed(4).replace(/0+$/,'').replace(/\.$/,'');
}
function ResultTable({data,caption}){
 if(!data)return null;
 const vertical=data.rows.length===1&&data.columns.length>3;
 const columns=vertical?['出力項目','値']:data.columns;
 const rows=vertical?data.columns.map((name,i)=>[name,valueText(data.rows[0][i],name)]):data.rows;
 return <div className="table-scroll method-example-scroll" tabIndex={0} role="region" aria-label={caption}><table className="data-table design-table method-example-table"><caption>{caption}</caption><thead><tr>{columns.map((c,i)=><th scope="col" key={i}>{c}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((value,j)=>j===0?<th scope="row" key={j}>{valueText(value,columns[j])}</th>:<td key={j}>{vertical?value:valueText(value,columns[j])}</td>)}</tr>)}</tbody></table></div>;
}
function QuantificationComparison(){return <Section title="数量化理論I〜IV類は、何が違う？"><div className="table-scroll"><table className="data-table design-table"><thead><tr><th scope="col">類</th><th scope="col">入力するもの</th><th scope="col">出てくるもの</th></tr></thead><tbody><tr><th scope="row"><PageLink href="#/statistics/method/quant1">I類</PageLink></th><td>カテゴリー＋時間・金額などの結果</td><td>カテゴリースコア・予測値</td></tr><tr><th scope="row"><PageLink href="#/statistics/method/quant2">II類</PageLink></th><td>カテゴリー＋既知のグループ</td><td>判別得点・グループの判別</td></tr><tr><th scope="row"><PageLink href="#/statistics/method/quant3">III類</PageLink></th><td>複数のカテゴリー回答</td><td>回答者やカテゴリーの位置</td></tr><tr><th scope="row"><PageLink href="#/statistics/method/quant4">IV類</PageLink></th><td>対象どうしの親近性</td><td>各対象の位置</td></tr></tbody></table></div><p>I・II類は説明したい結果があり、III・IV類は目的変数を置かず構造を見ます。I類はカテゴリーを使った回帰、II類はカテゴリーを使った判別分析、III類は多重対応分析と対応します。IV類は親近性から配置を作る方法で、一般の計量MDSとは計算が異なります。</p></Section>;}
function RankTestNames(){return <Section title="具体的な検定名と、使うデータ"><p>ノンパラメトリック検定は、正規分布など特定の分布の形を仮定しない検定の総称です。このページでは、順位や変化の方向を使う次の方法を扱います。レポートには、実際に使った検定名を書きます。</p><div className="table-scroll"><table className="data-table design-table"><thead><tr><th scope="col">データの関係</th><th scope="col">検定名</th></tr></thead><tbody><tr><td>独立した2群の値を順位で比べる</td><td>Mann–WhitneyのU検定</td></tr><tr><td>同じ人の2条件。差の大きさを順位にして比べる</td><td>Wilcoxonの符号付順位検定</td></tr><tr><td>同じ人の2条件。差がプラスかマイナスかを比べる</td><td>符号検定</td></tr><tr><td>独立した3群以上を順位で比べる</td><td>Kruskal–Wallis検定</td></tr><tr><td>同じ人の3条件以上を、その人の中の順位で比べる</td><td>Friedman検定</td></tr></tbody></table></div><p>ここで実際に計算するのは、<strong>Mann–WhitneyのU検定</strong>です。ほかの検定にそのまま置き換えることはできません。例えばWilcoxonの符号付順位検定には、差の分布の対称性などの前提があります。</p></Section>;}
function QuantificationEncoding({id,example}){
 if(!example.encoding)return null;
 return <><h3>カテゴリーを0/1のデータにする</h3><p>カテゴリーごとに列を作り、<strong>当てはまるところを1、当てはまらないところを0</strong>にします。こうした0/1の列を<strong>ダミー変数</strong>、カテゴリーごとの列を並べた表を<strong>指示行列（インジケーター行列）</strong>と呼びます。{id==='quant2'?'例えば利用場所が「自宅」なら、place_homeの列は1、place_officeの列は0です。':'例えば素材が「木」なら、material_woodの列は1、material_steelの列は0です。'}</p><ResultTable data={example.encoding} caption="元の回答 → 0/1の変換例"/><p>見比べやすいように、ここでは同じ回答の組み合わせを1行にまとめて表示しています。<strong>計算では、同じ回答をした人も含め、全員分の行を使います。</strong>0は「悪い」、1は「よい」という点数ではありません。一つだけ選ぶ質問なら、その質問のカテゴリー列の合計は1になります。</p>{id==='quant1'?<p>数量化理論I類では、形・素材を0/1にして、結果の<strong>time_secは秒数のまま</strong>使います。下のPython例の<code>C(shape)</code>と<code>C(material)</code>もこの変換を行います。計算に同じ情報を重複して入れないよう、丸・金属を基準としてその列を省きますが、丸・金属の人を除くわけではありません。</p>:id==='quant2'?<p>数量化理論II類では、経験・利用場所を0/1の列にします。<strong>正解のグループであるchoose_Aは別に保持</strong>し、説明に使う列へ混ぜません。この例では0＝選ばない、1＝選ぶ、というグループの目印です。</p>:<p>{id==='tsne'?'このt-SNEの例では、0/1の回答から人どうしの近さを計算し、回答者の配置を求めます。':'数量化理論III類では、各質問の回答を0/1にした表から、カテゴリーの配置を求めます。'}<strong>別に予測したい時間や、正解のグループを用意する必要はありません。</strong></p>}<p>「木＝1、金属＝2、樹脂＝3」のような整理用の番号を、大小や間隔に意味のある量として、そのまま計算に入れることとは異なります。</p></>;
}
export function MethodPractice({method}){
 const guide=methodGuides[method.id],example=exampleData.examples[method.id];
 const prompt=`自分のPCにインストール済みのPythonで「${method.name}」の計算を試します。${method.id}.pyとして保存して実行するコードを作り、処理のまとまりごとに何を確かめるかを説明してください。CSVはコードと同じフォルダーに保存します。必要なライブラリの準備と実行の命令も示してください。\n\n知りたいこと：${guide.question}\nデータの構造：${guide.unit}\n使うCSV：${method.id}.csv\n列の意味：\n${guide.fields.map(([name,meaning])=>`${name}：${meaning}`).join('\n')}\nrecord_idは元の行の目印です。説明変数に入れないでください。\n\n行数・型・欠測と、IDや行の重複が測定設計どおりかを最初に確認してください。除外・欠測補完・カテゴリーの数値化を勝手に決めず、必要なら理由を示してください。\n出力して意味を説明する項目：${outputGuideRows[method.id].map(row=>row[0]).join("、")}\n行う計算：${guide.calculation}${example.encoding?"\n元のカテゴリー回答と0/1に変換した指示行列を並べて示し、変換対象の列と、目的変数として別に保持する列を説明してください。表示用に同じ回答をまとめても、計算から参加者を削除しないでください。":""}\n\nデータを図で確認したうえで計算し、結果を見出し付きの表や図で出してください。各出力の単位・方向・分母を説明してください。\n最後に確認したいこと：${guide.next}\n実行環境のパッケージ名とバージョンも記録してください。`;
 return <><p className="lede">{guide.question}</p>{method.id.startsWith('quant')&&<QuantificationComparison/>}{method.id==='ranks'&&<RankTestNames/>}
 <Section title="1．どんなデータを用意する？"><p><strong>{guide.unit}</strong></p><div className="table-scroll"><table className="data-table design-table"><thead><tr><th scope="col">列</th><th scope="col">何を入れる？</th></tr></thead><tbody>{guide.fields.map(([name,meaning])=><tr key={name}><th scope="row">{name}</th><td>{meaning}</td></tr>)}</tbody></table></div><ResultTable data={example.input} caption={`入力例：全${example.count}行${example.count>6?'のうち先頭6行':''}`}/><p className="small-note">練習用の架空データです。人数・件数は計算例であり、研究に十分な標本数の目安ではありません。record_idは行の目印です。カテゴリーの略号や単位は上の表で確認してください。</p><div className="download-row"><PageLink href={`${base}data/method-examples/${method.id}.csv`} download>この入力データをCSVで保存 ↓</PageLink></div><QuantificationEncoding id={method.id} example={example}/></Section>
 <Section title="2．解析すると、何が出る？"><p>{guide.calculation}</p><EigenvalueExplanation id={method.id}/>{method.id==='tsne'&&<TsneConcept/>}<ResultTable data={example.output} caption="このデータをPythonで計算した出力例"/><ResultTable data={example.extra} caption="あわせて確認する出力"/>{example.scores&&<ResultTable data={example.scores} caption="各対象の主成分得点"/>}{example.more?.map(item=><ResultTable key={item.caption} data={item.data} caption={item.caption}/>)}{method.id==='pca'&&<PcaAxisChoice example={example}/>}<MethodCoordinatePlot id={method.id} example={example}/>{method.id==='tsne'&&<TsnePlots example={example}/>}{example.sampleProfiles&&<><CategoryPatternPlots id={method.id} example={example}/><details><summary>回答の組み合わせ・人数・サンプルスコアを照合する</summary><ResultTable data={example.sampleProfiles} caption="回答の組み合わせ別の人数とスコア"/><PageLink href={`${base}data/method-examples/${method.id}-scores.csv`} download>全員のサンプルスコアをCSVで保存 ↓</PageLink></details></>}<p className="small-note">下の実行例を動かした結果です。表示は小数を丸めています。「—」は、その欄の値を計算しないことを表します。座標の向きや丸めの末尾は、環境によって変わる場合があります。</p></Section>
 <Section title="3．結果をどう読む？"><AnalysisOutputReading id={method.id}/>{guide.read.map(text=><p key={text}>{text}</p>)}<p className="note"><strong>次にすること</strong><br/>{guide.next}</p><p>{method.note}</p><PageLink href="#/statistics/checks">解析前後の注意点を確認する →</PageLink>{method.id==='anova'&&<><h3>一元・二元・多元の違い</h3><p>画面A・B・Cという一つの項目なら一元配置。サイズ×コントラストなら二元配置。サイズ×コントラスト×余白なら三元配置で、複数の要因を扱うものを多元配置と呼びます。二元以上では、それぞれの主効果に加え、組み合わせによって違いが変わる交互作用も調べます。</p><p><PageLink href="#/statistics/experiments">04の生データから主効果・交互作用を計算する例へ →</PageLink></p></>}{['quant3','mca','pca'].includes(method.id)&&<p><PageLink href="#/statistics/method/tsne">t-SNEで配置を見る場合との違い →</PageLink></p>}{method.id==='quant3'&&<p><PageLink href="#/statistics/method/mca">多重対応分析（MCA）の説明へ →</PageLink></p>}{method.id==='mca'&&<p><PageLink href="#/statistics/method/quant3">数量化理論I〜IV類の中でのIII類の位置づけへ →</PageLink></p>}</Section>
 <Section title="4．PythonとAIで実行する"><p>コードはAIに任せて構いません。自分が伝えるのは、<strong>知りたいこと、1行の意味、列と単位、同じ対象を何度測ったか</strong>です。出力を見たら、上の例のように何を表す数字かを確かめます。</p><ol className="exercise-list"><li>作業用フォルダーを作り、上のCSVを保存する。</li><li>下の依頼例をAIに渡し、コードを<code>{method.id}.py</code>として同じフォルダーに保存し、自分のPCのPythonで実行する。</li><li>最初に行数・列・欠測・条件ごとの人数を確かめ、計算後は上の出力例と照合する。</li></ol><Prompt title="AIへの依頼例" text={prompt}/><details className="python-reference"><summary>確認用のPython実行例</summary><p>このコードには同じ架空データが含まれています。下のコードを保存するか、末尾のリンクからPythonファイルをダウンロードして実行できます。自分のCSVで使うときは、データを作る部分を読み込みに置き換えるようAIに依頼してください。</p><LocalPythonCommands packages={guide.packages} filename={`${method.id}.py`}/><p><strong>保存するPythonコード</strong></p><pre className="code-block"><code>{example.code}</code></pre><PageLink href={`${base}data/method-examples/${method.id}.py`} download>Pythonコードを保存 ↓</PageLink></details><p><strong>自分の研究に置き換えるとき：</strong>問い・行の意味・列の意味・測定の設計を実際のものに直して依頼してください。例の手法や前提が、そのまま合うとは限りません。</p><details><summary>この計算例を確認した環境</summary><p>Python 3.13。{Object.entries(exampleData.versions).map(([name,version])=>`${name} ${version}`).join('、')}。使用するパッケージは例によって異なります。</p></details></Section>
 </>;
}
