export const neuroscienceSources = {
  brain: ['NINDS：脳の構造と働き', 'https://www.ninds.nih.gov/health-information/public-education/brain-basics/brain-basics-know-your-brain'],
  brainAtlas: ['OpenStax：大脳の葉と、内側にある構造の位置', 'https://openstax.org/books/anatomy-and-physiology-2e/pages/13-2-the-central-nervous-system'],
  summation: ['Purvesほか：入力の加重と、ニューロンの発火', 'https://www.ncbi.nlm.nih.gov/books/NBK11104/'],
  summationFigure: ['OpenStax：空間的・時間的加重と発火の仕組み', 'https://openstax.org/books/introduction-behavioral-neuroscience/pages/2-4-mechanisms-of-neural-signaling'],
  convergence: ['Purvesほか：収束・発散などの神経科学用語', 'https://www.ncbi.nlm.nih.gov/books/NBK10981/'],
  synapseCount: ['Synaptic Signaling in Learning and Memory：錐体細胞のシナプス', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4743082/'],
  neuronTypes: ['OpenStax：ニューロンの構造と種類', 'https://openstax.org/books/anatomy-and-physiology-2e/pages/12-2-nervous-tissue'],
  neuronRoles: ['NIH：感覚・介在・運動ニューロンと情報伝達', 'https://www.ncbi.nlm.nih.gov/books/NBK20367/'],
  visualInput: ['Purvesほか：網膜から大脳皮質への視覚経路', 'https://www.ncbi.nlm.nih.gov/books/NBK10922/'],
  visualStreams: ['Purvesほか：一次視覚野から広がる二つの経路', 'https://www.ncbi.nlm.nih.gov/books/NBK10884/'],
  visionAction: ['Goodaleほか（1991）：物の知覚と、物をつかむ動作の解離', 'https://pubmed.ncbi.nlm.nih.gov/1986306/'],
  motor: ['Purvesほか：運動を支える神経系', 'https://www.ncbi.nlm.nih.gov/books/NBK10995/'],
  basalLoop: ['Alexander（1994）：大脳基底核・視床・皮質の運動回路', 'https://pubmed.ncbi.nlm.nih.gov/7962489/'],
  memorySystems: ['Squire & Wixted（2011）：記憶の種類と、それを支える脳の仕組み', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3192650/'],
  neuron: ['NINDS：神経細胞の働き', 'https://www.ninds.nih.gov/sites/default/files/2025-05/NINDS_Life_and_Death_of_a_Neuron_Booklet_073024_B_FOR_ONLINE_0.pdf'],
  glia: ['Purvesほか：グリア細胞の基本的な役割', 'https://www.ncbi.nlm.nih.gov/books/NBK10869/'],
  oligodendrocytes: ['Leeほか（2012）：オリゴデンドロサイトによる軸索の代謝支援', 'https://www.nature.com/articles/nature11314'],
  microglia: ['Schaferほか（2012）：ミクログリアと発達期のシナプスの刈り込み', 'https://pubmed.ncbi.nlm.nih.gov/22632727/'],
  plasticity: ['Lüscher & Malenka（2012）：NMDA受容体に依存するLTPとLTD', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3367554/'],
  ltpExperiment: ['Bliss & Lømo（1973）：海馬の歯状回での長期増強', 'https://doi.org/10.1113/jphysiol.1973.sp010273'],
  ltpPathways: ['Zalutsky & Nicoll（1990）：同じ海馬の細胞に入る、二つの経路のLTP', 'https://pubmed.ncbi.nlm.nih.gov/2114039/'],
  selection: ['Wimmerほか（2015）：マウスの注意課題と視床の感覚選択', 'https://www.nature.com/articles/nature15398'],
  thalamus: ['Schmittほか（2017）：視床による前頭前野の活動の維持', 'https://www.nature.com/articles/nature22073'],
  pulvinar: ['Saalmannほか（2012）：注意と視床枕・視覚皮質の活動', 'https://pubmed.ncbi.nlm.nih.gov/22879517/'],
  astrocytes: ['Williamsonほか（2024年オンライン公開／2025年巻号）：アストロサイトと記憶の想起', 'https://www.nature.com/articles/s41586-024-08170-w'],
  stabilization: ['Dewaほか（2025）：アストロサイトの集団と記憶の再安定化', 'https://www.nature.com/articles/s41586-025-09619-2'],
  working: ['Panichelloほか（2024）：断続的な発火とワーキングメモリー', 'https://www.nature.com/articles/s41586-024-08139-9'],
  emotion: ['Pessoaほか（2002）：注意と情動的な顔の処理', 'https://pubmed.ncbi.nlm.nih.gov/12177449/'],
  mirrorMonkey: ['di Pellegrinoほか（1992）：サルの行為の実行と観察に反応するニューロン', 'https://pubmed.ncbi.nlm.nih.gov/1301372/'],
  mirrorHuman: ['Mukamelほか（2010）：人の行為の実行・観察に対する単一ニューロンの反応', 'https://pubmed.ncbi.nlm.nih.gov/20381353/'],
  mirrorDataset: ['Tiliほか（2025）：複数の前頭・頭頂領域で記録したミラーニューロンのデータ', 'https://www.nature.com/articles/s41597-025-05299-9'],
  mirrorActionUnderstanding: ['Thompsonほか（2022）：行為の識別と意図の推定を分けて調べる', 'https://pubmed.ncbi.nlm.nih.gov/35906896/'],
  mirrorLearning: ['Catmurほか（2007）：感覚と運動の学習による、観察への反応の変化', 'https://pubmed.ncbi.nlm.nih.gov/17716898/'],
  representationalDrift: ['Schoonoverほか（2021）：同じにおいへの神経活動が、時間とともに変わる', 'https://pubmed.ncbi.nlm.nih.gov/34108681/'],
  sleepReactivation: ['Wilson & McNaughton（1994）：経験に関わる海馬の細胞集団の、睡眠中の再活性化', 'https://pubmed.ncbi.nlm.nih.gov/8036517/'],
  sleepRipples: ['Girardeauほか（2009）：学習後の海馬のリップル活動への介入と空間記憶', 'https://www.nature.com/articles/nn.2384'],
  multisensory: ['Shamsほか（2000）：音によって、光の点滅の見え方が変わる', 'https://pubmed.ncbi.nlm.nih.gov/11130706/'],
  interoception: ['Critchleyほか（2004）：身体内部の状態を感じ取ることと神経活動', 'https://www.nature.com/articles/nn1176'],
  forgetting: ['Berryほか（2012）：ショウジョウバエの学習と忘却を調整するドーパミン', 'https://pubmed.ncbi.nlm.nih.gov/22578504/'],
  rewardPrediction: ['Schultzほか（1997）：報酬の予測とドーパミン神経の活動', 'https://pubmed.ncbi.nlm.nih.gov/9054347/'],
  motorAdaptation: ['Izawaほか（2012）：小脳と、動作の結果を予測する学習', 'https://pubmed.ncbi.nlm.nih.gov/22442085/'],
  individualDevelopment: ['Freundほか（2013）：遺伝的に同じマウスに生じる行動と脳の個体差', 'https://pubmed.ncbi.nlm.nih.gov/23661762/'],
  limbicConnections: ['Neuroscience Online：海馬・帯状皮質・連合野の接続', 'https://nba.uth.tmc.edu/neuroscience/s4/chapter05.html'],
  amygdalaConnections: ['Neuroscience Online：扁桃体と皮質・身体反応の回路', 'https://nba.uth.tmc.edu/neuroscience/s4/chapter06.html'],
  limbicSystem: ['Purvesほか：大脳辺縁系とPapez回路', 'https://www.ncbi.nlm.nih.gov/books/NBK11060/'],
  hippocampalLesion: ['Bayleyほか（2005）：記憶障害と、海馬・内側側頭葉の損傷範囲', 'https://pubmed.ncbi.nlm.nih.gov/15924865/'],
  episodicRecall: ['Kirwanほか（2008）：内側側頭葉損傷後の、最近と過去の出来事の想起', 'https://pubmed.ncbi.nlm.nih.gov/18252820/'],
  patternCompletion: ['Hornerほか（2015）：海馬のパターン補完と皮質での記憶の再現', 'https://www.nature.com/articles/ncomms8462'],
  amygdalaMemory: ['Inmanほか（2017年オンライン公開／2018年巻号）：扁桃体刺激と翌日の記憶', 'https://pubmed.ncbi.nlm.nih.gov/29255054/'],
  creativity: ['Beatyほか（2015）：アイデア生成時の脳ネットワークの協調', 'https://www.nature.com/articles/srep10964'],
  curiosityMemory: ['Gruberほか（2014）：好奇心と、その後の記憶成績', 'https://pubmed.ncbi.nlm.nih.gov/25284006/'],
  consciousness: ['Cogitate Consortiumほか（2025）：意識に関する二つの理論の比較実験', 'https://www.nature.com/articles/s41586-025-08888-1'],
  note: ['蘆澤雄亮：3-04 脳の構造とデザイン', 'https://note.com/yashizawa/n/n0c622c5f85d5?magazine_key=m2e7e4bc1b5ae'],
};
