// Priority is an editorial choice for this introductory course, not an evidence grade.
// Comparisons describe study designs; they do not report newly collected observations.
export const psychologyAdditionalEffects = [
  {
    id:'weber', group:'知覚・注意', priority:'core', name:'ウェーバーの法則', english:'Weber’s law',
    what:'重い荷物では、少し重さを足しても気づきにくい。違いに気づくために必要な変化量が、元の刺激の強さにおおむね比例するという関係。',
    compare:'基準の重さを何段階か用意し、どれだけ足すと違いに気づくかを測る。「気づく変化量÷元の重さ」を比べる。',
    limit:'成り立つ刺激の範囲がある。ごく弱い刺激・強い刺激などでも、いつも同じ比率になるわけではない。', refs:['sensation'],
  },
  {
    id:'sensory-adaptation', group:'知覚・注意', priority:'core', name:'感覚順応', english:'Sensory adaptation',
    what:'同じにおいの部屋にいると、初めほど強く感じなくなる。刺激が続くことで、感覚の反応や感度が変わる。',
    compare:'同じ刺激に触れる前後で、刺激の強さの評定や、弱い刺激を検出できる割合を比べる。',
    limit:'単に注意を向けなくなったことや、後に出てくる「馴化」と区別する。反応が減ったというだけでは仕組みを特定できない。', refs:['sensation'],
  },
  {
    id:'gestalt-grouping', group:'知覚・注意', priority:'core', name:'ゲシュタルトの群化原理', english:'Gestalt principles of grouping',
    what:'近い点や、同じ色の点は、ひとまとまりに見えやすい。近接・類同・よい連続など、部分をまとめて見る手がかりがある。',
    compare:'点の数をそろえ、間隔や色だけを変える。どの点が同じまとまりに見えるか答えてもらう。',
    limit:'複数の手がかりが競合することもある。「近ければ必ず同じグループに見える」という絶対的な規則ではない。', refs:['gestaltPrinciples'],
  },
  {
    id:'mcgurk', group:'知覚・注意', priority:'field', name:'マガーク効果', english:'McGurk effect',
    what:'声と口の動きが食い違う動画を見ると、実際の声とは違う音節に聞こえる場合がある。聞こえ方にも視覚が関わる。',
    compare:'同じ音声を、音だけ／一致する口の動き／食い違う口の動きで提示し、何と聞こえたかを比べる。',
    limit:'全員に起きるわけではない。音声・映像・言語・個人によって違いがあり、一つの動画だけで能力を判定しない。', refs:['mcgurk'],
  },
  {
    id:'ventriloquism', group:'知覚・注意', priority:'advanced', name:'腹話術効果', english:'Ventriloquism effect',
    what:'別の場所から出ている音でも、同時に動く口や物の側から聞こえたように感じることがある。',
    compare:'音と光の位置をずらして提示し、音だけのときと、音の位置の回答を比べる。映像の見えやすさも変える。',
    limit:'視覚がいつも勝つわけではない。各感覚の位置情報がどれほど確かかによって、影響の受け方が変わる。', refs:['ventriloquism'],
  },
  {
    id:'attentional-blink', group:'知覚・注意', priority:'field', name:'注意の瞬き', english:'Attentional blink',
    what:'文字などが高速で次々に出る中で、標的を一つ見つけた直後の数百ミリ秒に、二つ目の標的を見落としやすくなることがある。',
    compare:'二つの標的の時間間隔を変える。一つ目を正しく答えた試行で、二つ目の正答率を比べる。',
    limit:'目のまばたきのことではない。時間間隔と成績の関係を見て判断し、一般的な「集中力切れ」と同一視しない。', refs:['attentionalBlink'],
  },
  {
    id:'popout', group:'知覚・注意', priority:'field', name:'ポップアウト（視覚探索）', english:'Pop-out in visual search',
    what:'青い点の中の赤い点のように、ある特徴が周囲と違う対象が、すぐ目に入ることがある。',
    compare:'周囲の項目数を増やして、標的を見つける時間を測る。色だけが違う場合と、色と形の組み合わせで探す場合を比べる。',
    limit:'目立つ色を使えば必ず見つかるとは限らない。背景との違い、視認性、同時に目立つ物の数なども関わる。', refs:['visualSearch'],
  },
  {
    id:'simon', group:'知覚・注意', priority:'advanced', name:'サイモン効果', english:'Simon effect',
    what:'色に応じて左右のキーを押すとき、色とは無関係な「刺激が出た側」も反応に影響する。',
    compare:'同じ色を画面の左右に出し、刺激位置と押すキーの側が一致／不一致の反応時間を比べる。',
    limit:'色とキーの対応を参加者間で入れ替え、利き手や練習も確認する。位置を答える課題とは区別する。', refs:['simon'],
  },
  {
    id:'cocktail-party', group:'知覚・注意', priority:'field', name:'カクテルパーティー効果', english:'Cocktail-party effect',
    what:'周囲で複数の人が話していても、一人の会話を選んで聞ける。たくさんの音の中から、必要な情報に注意を向ける現象。',
    compare:'複数の音声を同時に流し、指定した話者の言葉をどれだけ報告できるか調べる。話者の位置や声の違いを変える。',
    limit:'不要な音を完全に遮断できるわけではない。雑音の大きさや聴力なども成績に関わる。', refs:['sensation'],
  },
  {
    id:'motion-aftereffect', group:'知覚・注意', priority:'field', name:'運動残効', english:'Motion aftereffect',
    what:'一方向に流れる模様をしばらく見た後、止まった模様が反対向きに動くように見えることがある。',
    compare:'動く模様を見る条件と静止模様を見る条件の後で、静止画の動く方向や、そう見える時間を答えてもらう。',
    limit:'目の疲れという言葉だけでは説明できない。見る位置、模様、動きなどをそろえて調べる。', refs:['motionAftereffect'],
  },
  {
    id:'levels-processing', group:'記憶・学習', priority:'core', name:'処理水準効果', english:'Levels-of-processing effect',
    what:'単語の文字の形だけを見るより、意味を考えて読んだほうが、後で思い出しやすい場合がある。',
    compare:'同じ単語について、見た目を判断する課題／意味を判断する課題を行い、後の記憶成績を比べる。',
    limit:'「深く考えれば何でも覚えられる」ではない。学習時間や、後で求められる答え方もそろえる。', refs:['memoryEnhancement'],
  },
  {
    id:'self-reference', group:'記憶・学習', priority:'field', name:'自己参照効果', english:'Self-reference effect',
    what:'「この言葉は自分に当てはまるか」と考えた情報が、別の判断をした情報より記憶に残りやすい場合がある。',
    compare:'形容詞を、自分に当てはまるか／意味が近いかなどで判断してもらい、後の再生数を比べる。',
    limit:'自分に関係させれば、あらゆる内容で必ず有利とは限らない。比較する課題の難しさや考える量も確認する。', refs:['selfReference'],
  },
  {
    id:'context-memory', group:'記憶・学習', priority:'field', name:'文脈依存記憶', english:'Context-dependent memory',
    what:'覚えたときと同じ場所などが、思い出す手がかりになることがある。',
    compare:'覚える場所とテストする場所を組み合わせ、場所が同じ条件／違う条件で再生数を比べる。',
    limit:'どんなテストでも同じ強さで現れるわけではない。「試験会場で勉強しなければならない」という意味でもない。', refs:['contextMemory'],
  },
  {
    id:'proactive-interference', group:'記憶・学習', priority:'core', name:'順向干渉', english:'Proactive interference',
    what:'古いパスワードが先に出てきて、新しいものを思い出しにくい。前に覚えたことが、後の記憶を邪魔する。',
    compare:'似た単語対を先に覚えた群と、覚えていない群で、新しい単語対の再生数を比べる。',
    limit:'単に新しい内容を学べていない可能性と区別する。干渉の向きは「古い記憶→新しい記憶」。', refs:['memoryProblems'],
  },
  {
    id:'retroactive-interference', group:'記憶・学習', priority:'core', name:'逆向干渉', english:'Retroactive interference',
    what:'新しいパスワードを覚えた後、古いものを思い出しにくくなる。後で覚えたことが、前の記憶を邪魔する。',
    compare:'最初の単語対を覚えた後、似た別の単語対を学ぶ群と、学ばない群で、最初の記憶を比べる。',
    limit:'時間が過ぎたことだけによる変化と区別する。干渉の向きは「新しい記憶→古い記憶」。', refs:['memoryProblems'],
  },
  {
    id:'false-memory', group:'記憶・学習', priority:'core', name:'虚記憶', english:'False memory',
    what:'見聞きしていないことを、経験したこととして思い出す場合がある。本人がうそをついているとは限らない。',
    compare:'実際に提示した内容と、後で「見た」と答えた内容を照合する。誤った情報を後から与える条件などを比べる。',
    limit:'実験で誤りが起きることから、特定の人の記憶が正しいか間違いかを決められない。', refs:['memoryProblems'],
  },
  {
    id:'tongue-tip', group:'記憶・学習', priority:'advanced', name:'舌先現象', english:'Tip-of-the-tongue phenomenon',
    what:'名前を知っている感覚があり、最初の音なども浮かぶのに、言葉全体が出てこないことがある。',
    compare:'定義から単語を答える課題で、出てこない感覚、部分的に分かる音、後で答えを認識できたかを記録する。',
    limit:'「知っている気がする」という報告だけでは、実際に覚えていたとは確定できない。後の正答などと照らす。', refs:['tongueTip'],
  },
  {
    id:'picture-superiority', group:'記憶・学習', priority:'field', name:'画像優位性効果', english:'Picture-superiority effect',
    what:'物の名前を文字で読むより、その物の画像を見たほうが、後で覚えている場合がある。',
    compare:'同じ対象を画像／文字で提示し、提示時間をそろえて、後の再生や再認の成績を比べる。',
    limit:'複雑な図や抽象的な内容にも、そのまま当てはまるとは限らない。画像の分かりやすさも確認する。', refs:['pictureSuperiority'],
  },
  {
    id:'semantic-priming', group:'記憶・学習', priority:'field', name:'意味プライミング', english:'Semantic priming',
    what:'意味が関連する言葉に触れると、次の言葉を認識する反応が速くなることがある。例えば「医者」と「看護師」のような関係。',
    compare:'関連する単語の組／関連しない単語の組を用意し、実在する単語かを判断する時間と誤りを比べる。',
    limit:'単語の長さや出現頻度をそろえる。単語判断の促進を、無意識に人の複雑な行動を操れる証拠とはしない。', refs:['semanticPriming'],
  },
  {
    id:'classical-conditioning', group:'記憶・学習', priority:'core', name:'古典的条件づけ', english:'Classical conditioning',
    what:'食べ物と繰り返し組み合わされた音だけで、唾液が出るようになる。刺激同士の関係を学ぶ。',
    compare:'音と食べ物が結びつく条件／結びつかない条件で、後に音だけを出したときの反応を比べる。',
    limit:'単に同時に出せば同じように学習するとは限らない。どれだけ予告になるかも重要。', refs:['classical'],
  },
  {
    id:'operant-conditioning', group:'記憶・学習', priority:'core', name:'オペラント条件づけ', english:'Operant conditioning',
    what:'ある行動の後に起きたことによって、次にその行動をする頻度が変わる。行動が増える働きを「強化」という。',
    compare:'行動に応じて結果が返る条件を変え、その行動の回数や割合がどう変化するか記録する。',
    limit:'強化は本人が喜んだかではなく、行動が増えたかで判断する。「負の強化」は罰ではなく、嫌な刺激がなくなることで行動が増えること。', refs:['operant'],
  },
  {
    id:'habituation', group:'記憶・学習', priority:'core', name:'馴化', english:'Habituation',
    what:'害のない同じ音が繰り返されると、振り向くなどの反応が小さくなる。単純な学習の一つ。',
    compare:'同じ刺激への反応を繰り返し記録する。休憩後や別の刺激への反応も調べ、反応低下の原因を確かめる。',
    limit:'感覚器が反応しにくくなった感覚順応や、筋肉の疲労による変化とは区別する。', refs:['habituation'],
  },
  {
    id:'generalization', group:'記憶・学習', priority:'field', name:'刺激般化', english:'Stimulus generalization',
    what:'学習に使った音だけでなく、似た高さの音にも反応するようになることがある。',
    compare:'学習した刺激から少しずつ特徴を変え、それぞれへの反応の大きさや割合を図にする。',
    limit:'似ていると判断する特徴は課題や経験で変わる。区別する学習である「刺激弁別」と一緒に考える。', refs:['classical'],
  },
  {
    id:'extinction-recovery', group:'記憶・学習', priority:'field', name:'消去・自発的回復', english:'Extinction / Spontaneous recovery',
    what:'学習した反応が、予告していた刺激や強化がなくなると弱まることを消去という。弱まった反応が、時間を空けると戻る場合がある。',
    compare:'学習後に消去の手順を行い、反応の減少と、休憩を挟んだ後の反応を記録する。',
    limit:'消去は、記憶が完全に消えたことを意味しない。元の学習や状況によって反応が戻る場合がある。', refs:['classical'],
  },
  {
    id:'partial-reinforcement', group:'記憶・学習', priority:'field', name:'部分強化消去効果', english:'Partial-reinforcement extinction effect',
    what:'毎回強化された行動より、時々だけ強化された行動のほうが、強化がなくなってからも続きやすい場合がある。',
    compare:'毎回／一部の回だけ強化する条件を作る。その後どちらも強化をやめ、行動が減るまでの経過を比べる。',
    limit:'強化の回数や間隔、学習の量も関わる。あらゆる人の行動が「時々ほめる」だけで続くという法則ではない。', refs:['operant'],
  },
  {
    id:'observational-learning', group:'記憶・学習', priority:'core', name:'観察学習（モデリング）', english:'Observational learning / Modeling',
    what:'自分で試す前でも、他者が行動する様子や、その結果を見ることで、行動の仕方を学ぶことがある。',
    compare:'手本を見た群／見ていない群で、後に同じ操作をできるか、どんな行動を選ぶかを比べる。',
    limit:'見た行動を必ずまねるわけではない。学んだことと、その場で実行することも区別する。', refs:['modeling'],
  },
  {
    id:'representativeness', group:'判断・意思決定', priority:'core', name:'代表性ヒューリスティック', english:'Representativeness heuristic',
    what:'「いかにもその職業らしい」といった典型例との似かよい方で、どの集団に属するかを判断することがある。',
    compare:'人物の説明の典型らしさと、各職業の人数の情報を変え、所属の予想を比べる。',
    limit:'似ていることと、確率が高いことは同じではない。もっともらしい人物像自体に偏りがないかも確認する。', refs:['heuristics'],
  },
  {
    id:'base-rate-neglect', group:'判断・意思決定', priority:'core', name:'基準率無視', english:'Base-rate neglect',
    what:'目立つ個別の情報に引かれ、もともと各種類がどのくらい存在するかという割合を、判断に十分使わないことがある。',
    compare:'個別の手がかりを同じにして、集団の構成比を変える。確率の見積もりが、その違いをどれだけ反映するか調べる。',
    limit:'基準率をいつも完全に無視するとは限らない。割合を人数で示すなど、情報の伝え方も影響する。', refs:['heuristics'],
  },
  {
    id:'conjunction-fallacy', group:'判断・意思決定', priority:'field', name:'連言錯誤', english:'Conjunction fallacy',
    what:'人物の説明に合うと、「銀行員で、活動家でもある」を「銀行員である」より起こりやすいと答える場合がある。',
    compare:'人物の説明を読み、単独の条件と、二つを同時に満たす条件の確率を比べてもらう。',
    limit:'二つを同時に満たす人は、片方を満たす人の一部。確率はそれを超えないが、質問の言葉がどう理解されたかも確認する。', refs:['conjunction'],
  },
  {
    id:'hindsight', group:'判断・意思決定', priority:'core', name:'後知恵バイアス', english:'Hindsight bias',
    what:'結果を知った後で、「初めからそうなると思っていた」「予測できたはずだ」と感じやすくなる。',
    compare:'結果を知らせる群／知らせない群で、その結果を事前にどれほど予測できたと思うかを比べる。',
    limit:'後からの説明と、当時の予測を区別する。予測を事前に記録すると、実際に何を考えていたか照合できる。', refs:['hindsight'],
  },
  {
    id:'endowment', group:'判断・意思決定', priority:'field', name:'保有効果', english:'Endowment effect',
    what:'同じ品物でも、自分が持っている物を手放すときの希望額が、持っていない物を買うときの希望額より高くなる場合がある。',
    compare:'品物を持つ群／持たない群を無作為に分け、実際の取引に結びつく売値と買値を比べる。',
    limit:'所有への愛着だけで説明が決まるわけではない。取引経験、質問の理解、売買の手順も確認する。', refs:['endowment'],
  },
  {
    id:'default', group:'判断・意思決定', priority:'field', name:'デフォルト効果', english:'Default effect',
    what:'あらかじめ選ばれている選択肢が、そのまま選ばれやすくなることがある。',
    compare:'同じ選択肢で、最初に選択されている項目だけを変え、最終的な選択割合を比べる。',
    limit:'変更の手間や「推奨されている」という受け取り方も関わる。初期設定を隠したり、変更を妨げたりしてよい理由にはならない。', refs:['defaults'],
  },
  {
    id:'choice-overload', group:'判断・意思決定', priority:'advanced', name:'選択肢過多効果', english:'Choice-overload effect',
    what:'選択肢が増えると、選ぶのをやめたり、選択後の満足が下がったりする場合がある。',
    compare:'選択肢が少ない／多い条件で、選んだ割合、時間、満足度を比べる。魅力的な品物の有無もそろえる。',
    limit:'研究をまとめると結果には大きな違いがある。「選択肢は少ないほどよい」とは言えず、好みの明確さや選びやすさも関わる。', refs:['choiceOverload'],
  },
  {
    id:'dunning-kruger', group:'判断・意思決定', priority:'advanced', name:'ダニング＝クルーガー効果', english:'Dunning–Kruger effect',
    what:'課題の成績が低い人ほど、自分の相対的な成績を大きく高めに見積もる、という形のずれが報告された。',
    compare:'実際の課題成績と、本人が予想する順位・得点を同じ人から取り、ずれと成績の関係を調べる。',
    limit:'課題や分析方法で結果が変わり、統計的な要因も検討が必要。「愚かさの山」から谷へ進む図や、自信のある人を見下す説明は原研究の結果ではない。', refs:['dunningKruger','dunningReanalysis'],
  },
  {
    id:'dissonance', group:'対人・集団', priority:'core', name:'認知的不協和', english:'Cognitive dissonance',
    what:'「健康が大事」と考えながら不健康な行動をするなど、考えと行動が食い違うと、不快さを減らすため説明や態度を変える場合がある。',
    compare:'自分で選んだ感覚や、行動を正当化できる理由の大きさを変え、その後の態度を比べる。',
    limit:'矛盾があれば必ず同じ変化が起きるわけではない。態度の変化だけから、内側の不快さの原因を決めない。', refs:['dissonance'],
  },
  {
    id:'attribution', group:'対人・集団', priority:'core', name:'根本的な帰属の誤り', english:'Fundamental attribution error',
    what:'他人が遅刻すると「だらしない人」と考え、交通の遅れなど、その人が置かれた状況を軽く見てしまうことがある。',
    compare:'本人が選んだ行動／指示された行動を示し、そこから性格や態度をどのくらい推測するか比べる。',
    limit:'文化や状況で傾向が違う。性格の影響がないという意味でもなく、本人側と状況側の両方を検討する。', refs:['attribution'],
  },
  {
    id:'self-serving', group:'対人・集団', priority:'field', name:'自己奉仕バイアス', english:'Self-serving bias',
    what:'成功は自分の力、失敗は課題や運などのせいと説明する傾向が見られることがある。',
    compare:'成功した場合と失敗した場合で、結果の原因を能力・努力・運・難しさなどへどれだけ割り当てるか比べる。',
    limit:'原因の説明が必ず誤りとは限らない。実際の難しさや本人の事前予想も考慮する。', refs:['attribution'],
  },
  {
    id:'ingroup', group:'対人・集団', priority:'core', name:'内集団ひいき', english:'In-group favoritism',
    what:'同じグループに入っているというだけでも、相手に多く配分するなど、自分側の集団を優遇する場合がある。',
    compare:'簡単な基準で集団を分け、匿名の相手への配分が、同じ集団と別の集団で違うか調べる。',
    limit:'内集団の優遇と、外集団への敵意は同じではない。資源の競争や関係性によっても変わる。', refs:['minimalGroups'],
  },
  {
    id:'outgroup', group:'対人・集団', priority:'field', name:'外集団同質性効果', english:'Out-group homogeneity effect',
    what:'自分たちにはいろいろな人がいるのに、別の集団の人は「みんな似ている」と捉える場合がある。',
    compare:'各集団の人の特徴を評定し、どの程度ばらつきがあると思うかを、同じ尺度で比べる。',
    limit:'集団への知識や実際の構成が違う場合もある。すべての集団・特徴で必ず起こるわけではない。', refs:['outgroup'],
  },
  {
    id:'group-polarization', group:'対人・集団', priority:'field', name:'集団極性化', english:'Group polarization',
    what:'似た方向の意見を持つ人が話し合うと、話し合い後の意見が、初めよりその方向へ強まる場合がある。',
    compare:'話し合い前後に各人の意見を数値で答えてもらい、初めの平均からどちらへ動いたか調べる。',
    limit:'全員の意見が必ず極端になるわけではない。参加者の初期意見、出された情報、議論の進め方も確認する。', refs:['social'],
  },
  {
    id:'reactance', group:'対人・集団', priority:'field', name:'心理的リアクタンス', english:'Psychological reactance',
    what:'「絶対にこれを選べ」と自由を奪われたように感じると、反発したり、禁じられた選択肢を選びたくなったりする場合がある。',
    compare:'同じ内容を、強制的な表現／選択を認める表現で伝え、怒り、反論、選択や態度を比べる。',
    limit:'指示への反対がすべてリアクタンスとは限らない。内容への合理的な反対とも区別する。', refs:['reactance'],
  },
  {
    id:'foot-in-door', group:'対人・集団', priority:'advanced', name:'フット・イン・ザ・ドア法', english:'Foot-in-the-door technique',
    what:'小さな依頼を引き受けた後で、関連する大きな依頼も引き受けやすくなる場合がある。',
    compare:'小さな依頼を先にする群／しない群で、同じ大きな依頼を受ける割合を比べる。',
    limit:'必ず承諾を得られる技法ではない。研究結果を、人が断りにくくなる仕組みづくりへ無批判に使わない。', refs:['footInDoor'],
  },
  {
    id:'obedience', group:'対人・集団', priority:'core', name:'権威への服従', english:'Obedience to authority',
    what:'権威があると受け取った相手の指示によって、自分ではためらう行動を続ける場合がある。ミルグラムの研究が有名。',
    compare:'歴史的研究では、指示者の位置や相手との距離などを変え、参加者がどこまで指示に従ったかを比べた。',
    limit:'条件ごとに結果が異なり、「人は誰でも従う」とは言えない。強い苦痛や欺瞞を伴う原手順を、授業で再現する実習にはしない。', refs:['milgram','obedience'],
  },
  {
    id:'stereotype-threat', group:'対人・集団', priority:'advanced', name:'ステレオタイプ脅威', english:'Stereotype threat',
    what:'自分の所属集団への否定的な見方を意識すると、その見方を裏づけるのではないかという懸念が、課題成績に関わる場合がある。',
    compare:'課題の説明などで集団への見方を意識させる条件／させない条件を作り、同じ課題の成績を比べる。',
    limit:'対象・課題によって結果が違い、出版バイアスも議論される。一つの効果だけで現実の集団間の成績差全体を説明しない。', refs:['stereotypeThreat'],
  },
  {
    id:'undermining', group:'動機づけ・情動', priority:'field', name:'アンダーマイニング効果', english:'Undermining effect / Overjustification effect',
    what:'もともと好きで取り組んでいた活動でも、報酬を目的にするようになると、報酬がなくなった後の自発的な取り組みが減る場合がある。',
    compare:'報酬の有無や条件を変え、報酬が終わった後に自由時間で取り組む時間や、興味の評定を比べる。',
    limit:'報酬はいつも意欲を下げるわけではない。予告の有無、報酬の種類、成果との結びつけ方などで結果が違い、研究の整理方法にも議論がある。', refs:['rewardMotivation','rewardDebate'],
  },
  {
    id:'helplessness', group:'動機づけ・情動', priority:'core', name:'学習性無力感', english:'Learned helplessness',
    what:'自分の行動で変えられない不快な出来事の後、状況を変えられるようになっても、働きかけが減る現象が研究されてきた。',
    compare:'歴史的な動物研究では、不快な刺激を止められる条件／止められない条件の後で、回避行動を比べた。',
    limit:'仕組みの説明は更新され、状況を制御できることの学習も重視される。人の不活動を一語で決めつけたり、不快な体験を与える実習にしたりしない。', refs:['helplessness'],
  },
  {
    id:'affect-misattribution', group:'動機づけ・情動', priority:'field', name:'感情の誤帰属', english:'Misattribution of affect',
    what:'天気などで生じた今の気分を、評価している対象への感情だと思い、その対象の評価に使う場合がある。',
    compare:'気分が違う条件で同じ対象を評価してもらう。気分の別の原因に気づかせたときに、評価差が変わるかも調べる。',
    limit:'気分と評価に相関があるだけでは、原因の取り違えまで確定しない。評価対象が本当に気分を変えた可能性もある。', refs:['moodAttribution'],
  },
  {
    id:'mood-congruent', group:'動機づけ・情動', priority:'field', name:'気分一致記憶', english:'Mood-congruent memory',
    what:'楽しい気分のときは楽しい出来事など、その時の気分と合う内容を思い出しやすくなる場合がある。',
    compare:'気分の異なる条件で、肯定的・否定的な内容をどれだけ思い出すか比べる。元々覚えた量もそろえる。',
    limit:'同じ気分で覚えて思い出す「気分依存記憶」とは別。材料や課題によって強さが変わる。', refs:['moodMemory'],
  },
  {
    id:'ego-depletion', group:'動機づけ・情動', priority:'advanced', name:'自我消耗', english:'Ego depletion',
    what:'自制を要する課題の後は、次の自制課題の成績も下がる、という仮説と現象名。再現性が議論されている。',
    compare:'最初に自制が必要な課題／比較課題を行い、その後の同じ課題の成績を比べる。',
    limit:'2016年の事前登録された多施設追試では、用いた手順で明確な効果は確認されなかった。「意志力は使うと減る燃料」と確定した知識として教えない。', refs:['depletion'],
  },
  {
    id:'reappraisal', group:'動機づけ・情動', priority:'field', name:'認知的再評価', english:'Cognitive reappraisal',
    what:'出来事の捉え方を変えることで、感情の生じ方を変えようとする過程。例えば、映像を作り物として見るなど。',
    compare:'同じ映像を、そのまま見る／捉え直して見る条件で、感情の評定、表情、生理反応を比べる。',
    limit:'つらい出来事を無理に前向きに考えれば解決する、という意味ではない。状況や測る指標で結果は違う。', refs:['reappraisal'],
  },
  {
    id:'object-permanence', group:'発達', priority:'core', name:'対象の永続性', english:'Object permanence',
    what:'おもちゃが布の下に隠れても、なくなったわけではないと捉えること。乳児の認知発達を調べる重要な話題。',
    compare:'物を隠した後に探す行動や、予想と違う出来事を見つめる時間を、年齢や課題条件で比べる。',
    limit:'手で探せないことと、存在を捉えていないことは同じではない。運動や記憶など、課題に必要な力も考える。', refs:['developmentTheory'],
  },
  {
    id:'theory-of-mind', group:'発達', priority:'core', name:'心の理論（誤信念の理解）', english:'Theory of mind / False-belief understanding',
    what:'自分が知っていることを、相手も知っているとは限らない。他者が現実と違う考えを持つことを理解する能力を調べる。',
    compare:'登場人物の不在中に物を移し、その人物が戻ったらどこを探すと思うか聞く。記憶や言葉の理解も確かめる。',
    limit:'心の理論は誤信念課題だけでは測りきれない。一問の不正解で、共感や他者理解の能力全体を決めつけない。', refs:['falseBelief'],
  },
  {
    id:'attachment', group:'発達', priority:'core', name:'愛着', english:'Attachment',
    what:'特定の養育者などとの間に築く情緒的な結びつき。不安な場面で近づく、安心して周囲を探索する、といった行動から調べる。',
    compare:'研究では養育者との分離・再会時の行動や、日常場面の観察を記録し、その関係の特徴を検討する。',
    limit:'一生変わらない性格の分類ではない。一度の観察で親子を評価せず、年齢・文化・関係の文脈を考える。分離を伴う課題には専門的な手順と倫理審査が必要。', refs:['developmentStages'],
  },
  {
    id:'demand-characteristics', group:'研究・測定', priority:'core', name:'要求特性', english:'Demand characteristics',
    what:'参加者が「こう答えてほしい実験なのかな」と推測し、それに合わせたり、反発したりして反応を変えることがある。',
    compare:'説明の仕方や目的の伝わり方を検討し、参加者がどんな目的を推測したかも事後に確認する。',
    limit:'目的を隠せばすべて解決するわけではない。欺瞞の必要性、倫理審査、事後説明は03の手順と一緒に考える。', refs:['demand'],
  },
  {
    id:'experimenter-expectancy', group:'研究・測定', priority:'core', name:'実験者期待効果', english:'Experimenter expectancy effect',
    what:'実験する側の期待が、声のかけ方、扱い方、記録や採点などに入り、結果へ影響することがある。',
    compare:'測定担当者が条件を知る場合／知らない場合や、自動記録との一致を比べる。手順を統一し、採点時に条件を伏せる。',
    limit:'期待を持てば相手の能力が必ず変わる、という意味ではない。どの段階で影響が入ったかを切り分ける。', refs:['experimenter'],
  },
  {
    id:'placebo', group:'研究・測定', priority:'core', name:'プラセボ効果', english:'Placebo effect',
    what:'有効成分だけでなく、「効くかもしれない」という期待や処置の文脈が、痛みなどの経験に関わることがある。',
    compare:'研究では処置や説明の条件をそろえ、プラセボを受ける場合と受けない場合などの変化を比べる。',
    limit:'プラセボ群の改善には、自然な経過や平均への回帰も含まれうる。改善分すべてを期待の効果とせず、病気が治ると一般化しない。', refs:['placebo'],
  },
  {
    id:'social-desirability', group:'研究・測定', priority:'core', name:'社会的望ましさバイアス', english:'Social-desirability bias',
    what:'実際の行動や気持ちより、「よく見られそうな答え」を選んでしまうことがある。例えば、望ましい行動を多めに報告する。',
    compare:'匿名性や回答方法の条件を検討し、可能なら自己報告を行動記録など別の方法と照合する。',
    limit:'回答者が意識してうそをつく場合だけではない。尺度得点を使えば自動的に偏りを補正できるわけでもない。', refs:['desirability'],
  },
  {
    id:'regression-to-mean', group:'研究・測定', priority:'core', name:'平均への回帰', english:'Regression to the mean',
    what:'極端に高い・低い測定値の人を選ぶと、次の測定では平均に近づきやすい。心の変化がなくても起こりうる統計的な現象。',
    compare:'「最初の得点が低い人」だけの前後差で効果を決めず、同じ選び方をした比較群も用意する。',
    limit:'全員の得点が必ず平均へ戻るわけではない。測定の揺れなどで生じるので、改善をすべて指導や介入のおかげにしない。', refs:['regressionMean'],
  },
  {
    id:'hawthorne', group:'研究・測定', priority:'advanced', name:'ホーソン効果', english:'Hawthorne effect',
    what:'研究に参加したり観察されていると知ったりすること自体で、行動が変わる可能性を指して使われる言葉。',
    compare:'観察や研究参加の伝え方、記録する期間などを変えて、普段との行動の違いを調べる。',
    limit:'定義や結果が研究ごとに異なる。「見られると必ず頑張って成績が上がる」という確立した法則として扱わない。', refs:['hawthorne'],
  },
  {
    id:'publication-bias', group:'研究・測定', priority:'core', name:'出版バイアス', english:'Publication bias',
    what:'はっきりした結果が出た研究ほど公表されやすいと、読める論文だけでは効果が強く見える。参加者の心理ではなく、研究が伝わる過程の偏り。',
    compare:'事前に登録された研究や実施済み研究の記録と、公表された論文を照合する。結果による公表率の違いを調べる。',
    limit:'論文の数が多いだけでは十分ではない。事前登録や結果が出る前の査読、未公表研究の確認も大切。', refs:['publicationBias','registered'],
  },
];
