import PageLink from './PageLink.jsx';
import { Section, Prompt } from './Common.jsx';
const tools=[
 ['画面で操作する','jamovi','無料','デスクトップ版は無料。ブラウザーで使うjamovi Cloudは、無料枠と有料プランがある。','表を読み込み、メニューで検定や回帰を選ぶ。コードを書かずに試せる。','必要な手法・追加モジュールを確認し、設定と結果を一緒に保存する。',[['公式：無料で使える範囲','https://www.jamovi.org/faq.html'],['Cloudのプラン','https://www.jamovi.org/cloud.html']]],
 ['画面で操作する','JASP','無料','無料のオープンソースソフト。大学の有料契約がなくても利用できる。','表を読み込み、メニューから検定・回帰・ベイズ統計などを行う。','使いたいモデルやオプションに対応しているか確認する。選んだ設定の意味も理解する。',[['公式：JASPについて','https://jasp-stats.org/'],['機能一覧','https://jasp-stats.org/features/']]],
 ['表計算で行う','Excel','無料版あり／デスクトップ版は有料','Web版は無料で利用できる。分析ツールを使う統計解析では、デスクトップ版の利用環境・契約を確認する。','データの確認や集計、図の作成、分析ツールによる基本的な統計解析に使う。','無料のWeb版とデスクトップ版は機能が同じではない。複雑なモデルや繰り返し処理、解析の再現には別の道具も検討する。',[['Microsoft：無料Web版・プラン','https://www.microsoft.com/ja-jp/microsoft-365/excel'],['Microsoft：分析ツールの対応環境','https://support.microsoft.com/ja-jp/excel/use-the-analysis-toolpak-to-perform-complex-data-analysis']]],
 ['統計ソフトを使う','SPSS Statistics','有料','有料ライセンス。期間限定の体験版や学生向けの契約もある。大学の包括契約を使えるか確認する。','専用の画面で、集計・可視化・統計モデルの設定と結果の確認を行う。','追加機能は契約・エディションによって異なる。大学契約で個人負担がなくても、誰でも無料のソフトではない。',[['IBM：製品・料金・大学向けライセンス','https://www.ibm.com/products/spss-statistics']]],
 ['統計ソフトを使う','JMP','対象者は無料／一般向けは有料','対象の学生・教員・学術研究者はJMP Student Editionを無料で利用できる。資格確認や利用条件がある。','画面操作でデータの可視化、統計解析、実験計画などを行う。','学生だからすべての用途で無料、とは限らない。所属と利用目的がStudent Editionの条件に合うか確認する。',[['JMP：Student Editionと対象者','https://www.jmp.com/en/academic/jmp-student-edition'],['無料版の利用条件','https://www.jmp.com/en/academic/jmp-student-edition/faq']]],
 ['コードで行う','Python','無料','Python本体は無料。クラウド計算サービスなどを選ぶ場合は、その利用料が別にかかることがある。','ライブラリを組み合わせて、前処理・可視化・統計解析・予測を実行する。同じ処理の繰り返しにも向く。','Pythonそのものに全手法が入っているわけではない。下の一覧から、処理に合うライブラリを使う。',[['Python：利用について','https://www.python.org/about/'],['SciPyの公式資料','https://docs.scipy.org/doc/scipy/reference/stats.html']]],
 ['コードで行う','R','無料','R本体は無料。有料の開発環境やクラウドサービスを使う場合は、別途その条件を確認する。','統計解析のための言語と環境。分野ごとのパッケージや既存の研究コードを利用する。','共同研究者や研究分野の蓄積も選ぶ材料になる。Rで整った手法を、無理に別の言語へ移す必要はない。',[['R Project：Rについて','https://www.r-project.org/about.html'],['CRANの分野別一覧','https://cran.r-project.org/web/views/']]],
];
const libraries=[
 ['NumPy','数値計算の土台','配列、行列、乱数などを扱う。シミュレーションや数式に沿った計算。','https://numpy.org/doc/stable/'],
 ['pandas','表を読み、整える','CSVの読み込み、列の変換、欠測の確認、グループごとの集計。','https://pandas.pydata.org/docs/'],
 ['SciPy / scipy.stats','分布・検定を計算する','確率分布、t検定、順位検定、相関など。関数が対応あり／なしのどちらかを確認する。','https://docs.scipy.org/doc/scipy/reference/stats.html'],
 ['statsmodels','統計モデルを推定する','回帰、一般化線形モデル、混合効果モデルなど。係数・標準誤差・信頼区間・診断を調べる。','https://www.statsmodels.org/stable/index.html'],
 ['scikit-learn','予測や構造の探索','回帰・分類・PCA・クラスター分析、前処理、交差検証。係数のp値を読む統計ソフトと役割が同じとは限らない。','https://scikit-learn.org/stable/user_guide.html'],
 ['Matplotlib / seaborn','図で確かめる','散布図、ヒストグラム、箱ひげ図など。Matplotlibで細かく調整し、seabornで統計的な図を組み立てる。','https://seaborn.pydata.org/'],
 ['Prince','対応分析など','対応分析（CA）・多重対応分析（MCA）などの探索的な多変量解析。入力する表の形を確認する。','https://maxhalford.github.io/prince/'],
 ['semopy','関係の構造をモデル化する','構造方程式モデリング（SEM）。測定モデルや仮説を先に考える。','https://semopy.com/'],
 ['PyMC','ベイズモデルを組み立てる','事前分布とデータから事後分布を推定する。モデルの設定とサンプリングの診断も必要。','https://www.pymc.io/'],
];
export default function ToolsLesson(){return <><p className="eyebrow">07 / 統計解析を実施する方法</p><h1>統計解析を実施する方法</h1>
 <Section title="実施する方法の一覧"><p>まずは<strong>無料・有料・条件付きで無料</strong>を見分けましょう。「有料ソフトを大学の契約で使うこと」と「誰でも無料で使えること」は別です。購入前に、大学で使えるライセンスも確認してください。</p><p className="small-note">利用区分は2026年9月14日に公式情報で確認。料金・対象者・利用できる機能は変わることがあるため、各項目の公式リンクで最新の条件を確認してください。</p><div className="reference-list">{tools.map(([kind,name,cost,costNote,body,note,links])=><article key={name}><span className="eyebrow">{kind}</span><h3>{name}</h3><p><strong className="cost-label">{cost}</strong></p><p>{costNote}</p><p>{body}</p><p className="tool-detail">{note}</p><div className="source-links">{links.map(([label,url])=><PageLink href={url} key={url} target="_blank" rel="noreferrer">{label} ↗</PageLink>)}</div></article>)}</div></Section>
 <Section title="Pythonでは、ライブラリを組み合わせる"><p>ライブラリは、よく使う処理をまとめた道具箱です。例えば、pandasで表を読み、図で確認し、SciPyで検定する。複数の要因を一緒に扱うならstatsmodels、未知のデータへの予測を比較するならscikit-learn、と役割を分けて使います。</p><div className="reference-list libraries">{libraries.map(([name,role,body,url])=><article key={name}><h3>{name}</h3><strong>{role}</strong><p>{body}</p><PageLink href={url} target="_blank" rel="noreferrer">公式資料 ↗</PageLink></article>)}</div><p>有名なライブラリだからといって、自分の設計に必要な手法がすべて入っているとは限りません。対応のある検定か、どの推定方法か、欠測をどう扱うかなど、関数の仕様を公式資料で確認します。</p></Section>
 <Section title="Pythonは、自分のPCで動かす"><p>この教材では、各自のPCにインストール済みのPythonを使います。CSVとコードを作業用フォルダーに保存し、必要なライブラリをそのPython環境に入れて実行します。</p><div className="reference-list"><article><h3>エディターとPython実行環境</h3><p><strong className="cost-label">Pythonは無料／エディターによる</strong></p><p>使い慣れたエディターで.pyファイルを編集し、手元のPythonで実行します。コード・データ・実行結果と、ライブラリのバージョンを一緒に残します。</p><PageLink href="https://docs.python.org/3/tutorial/interpreter.html">Pythonファイルの実行 ↗</PageLink></article><article><h3>Jupyter Notebook / JupyterLab</h3><p><strong className="cost-label">無料</strong></p><p>手元でJupyterを使っている場合は、コード・文章・実行結果をノートにまとめる方法もあります。小さなまとまりの「セル」を順に実行し、途中の表や図を確認できます。</p><PageLink href="https://jupyter.org/">Jupyter ↗</PageLink></article></div><p>どちらで実行しても、解析の前提と出力の読み方は同じです。<PageLink href="#/statistics/python">Pythonの練習例</PageLink>で、ファイルの保存場所と実行方法を確認できます。</p></Section>
 <Section title="AIには、道具の選び方から聞く"><p>コードを頼む前に、使いたい手法とデータの構造を伝えます。ライブラリ名だけで依頼せず、「同じ人の繰り返し測定を扱えるか」「出力から何が読めるか」も確認しましょう。</p><Prompt text={'次の統計解析を実施する方法を比較してください。\n知りたいこと：【記入】\n検討している手法：【記入】\nデータの形・対象数・対応や繰り返し測定：【記入】\n使える環境：自分のPCのPython【OS・エディター・ほかに使えるソフトを記入】\nGUIで操作する方法とコードで行う方法を、無料・有料・学生向けの条件も含めて比較してください。Pythonの場合は、どのライブラリのどの機能を使うか、公式資料へのリンクとともに説明してください。必要なオプションや前提、再現のために保存するものも示してください。手法がデータに合うか不明なら、先に質問してください。'}/></Section>
 <Section title="手を動かしてみたいとき"><p>画面A・Bの架空データで、図を描き、平均差を検討する練習も用意しています。</p><PageLink className="next-link" href="#/statistics/python">Pythonの練習例へ →</PageLink></Section>
 </>;}
