import { useState } from 'react';

export function TsneConcept(){return <><h3>似た回答者を、近くに置いてみる</h3><p><strong>t-SNE（t-distributed Stochastic Neighbor Embedding）</strong>は、多くの項目で表されたデータを、主に2次元・3次元の図で見るための非線形次元削減法です。この例では、数量化理論III類と同じ60人の回答を使います。</p><ol className="exercise-list"><li>3つの質問への回答を9列の0/1にする。1行が1人です。</li><li>元の回答から、人どうしの「近さ」を確率で表す。</li><li>図の中の近さも確率で表し、両者のずれが小さくなるよう、点の位置を繰り返し動かす。</li></ol><p>この位置調整で求めるのは<strong>回答者の座標</strong>です。t-SNEにカテゴリーの名前を入れれば、そのカテゴリーの座標まで一緒に出るわけではありません。</p><h3>PCA・数量化理論III類とは、何が違う？</h3><div className="table-scroll"><table className="data-table design-table"><thead><tr><th>方法</th><th>この教材での入力</th><th>主に見るもの</th></tr></thead><tbody><tr><th><a href="#/statistics/method/pca">主成分分析（PCA）</a></th><td>幅・重さなどの量</td><td>ばらつきを表す軸。固有値・寄与率・累積寄与率、項目の重み。</td></tr><tr><th><a href="#/statistics/method/quant3">数量化理論III類</a></th><td>カテゴリー回答の0/1表</td><td>固有値問題から求める、カテゴリーと回答者のスコア。</td></tr><tr><th>t-SNE</th><td>今回は同じ0/1表。量的な特徴も使える</td><td>近い対象の関係を重視した配置。固有値・寄与率・累積寄与率は標準の出力にない。</td></tr></tbody></table></div><p>t-SNEの「t」は、図の中の近さを表すのにt分布を使うことに由来します。平均差を調べるt検定とは別の方法です。</p></>;}
const profiles=[['reading','wood','natural','読書・木・自然な印象','#cc2939'],['work','steel','sharp','仕事・金属・シャープ','#2865b0'],['chat','fabric','soft','会話・布・柔らかな印象','#347a57']];
export function TsnePlots({example}){
 const [selected,setSelected]=useState(1),plot=example.plots[selected];
 const rows=plot.points.rows,xs=rows.map(r=>r[1]),ys=rows.map(r=>r[2]);
 const xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);
 const scale=290/Math.max(xmax-xmin,ymax-ymin,.001),sx=x=>200+(x-(xmin+xmax)/2)*scale,sy=y=>175-(y-(ymin+ymax)/2)*scale;
 return <div className="tsne-plots"><h3>同じ60人でも、設定で配置が変わる</h3><p><strong>perplexity</strong>は、どのくらいの範囲の近所づきあいを重視するかに関わる設定です。人数より小さくする必要があります。<strong>random_state</strong>は乱数の種で、同じ条件の計算を再現するために記録します。この例は、最初の位置を乱数で決めています。</p><div className="segmented" role="group" aria-label="t-SNEの設定">{example.plots.map((item,i)=><button key={`${item.perplexity}-${item.seed}`} aria-pressed={i===selected} onClick={()=>setSelected(i)}>perplexity {item.perplexity}／種 {item.seed}</button>)}</div><figure className="method-coordinate"><figcaption aria-live="polite">perplexity＝{plot.perplexity}、random_state＝{plot.seed}。1点が1人。</figcaption><svg viewBox="0 0 400 370" role="img" aria-label={`60人のt-SNE配置。perplexity ${plot.perplexity}、乱数の種 ${plot.seed}。色は元の回答の組み合わせ。`}><rect x="30" y="15" width="340" height="325" fill="white" stroke="#ddd"/>{rows.map(r=><circle key={r[0]} cx={sx(r[1])} cy={sy(r[2])} r="4.5" fill={profiles.find(p=>p.slice(0,3).every((v,i)=>v===r[3+i]))?.[4]||'#999'} opacity=".8"><title>{`${r[0]}：${r.slice(3).join('・')}／座標 ${r[1].toFixed(2)}, ${r[2].toFixed(2)}`}</title></circle>)}<text x="200" y="364" textAnchor="middle">座標1</text><text x="17" y="178" textAnchor="middle" transform="rotate(-90 17 178)">座標2</text></svg></figure><ul className="category-legend">{profiles.map(p=><li key={p[0]}><span style={{color:p[4]}}>●</span> {p[3]}</li>)}<li><span style={{color:'#999'}}>●</span> ほかの組み合わせ</li></ul><p>色は元の回答を見分けるために付けました。<strong>t-SNEが発見した正解のグループではありません。</strong>同じ回答の人も一人ずつ計算に入れているため、初期配置や設定によって別の座標になることがあります。</p><p>まとまりの近さを元の回答と照合します。離れたまとまり同士の距離や、図の面積を、そのまま「違いの大きさ」「人数」とは読めません。各図は見やすい大きさに合わせているので、設定間で図上の距離を直接比べません。</p><p><a href={`${import.meta.env.BASE_URL}data/method-examples/tsne-coordinates.csv`} download>4設定・全60人の座標をCSVで保存 ↓</a></p></div>;
}
