export const webLinks = [
  ['/web/overview', '01　フロントエンドとバックエンド'],
  ['/web/document', '02　HTML・CSS・DOM'],
  ['/web/javascript', '03　JavaScriptとフレームワーク'],
  ['/web/database', '04　バックエンドとデータベース'],
  ['/web/cms', '05　CMSの仕組み'],
  ['/web/practice', '06　実際にインタラクションを実装するには？'],
];
export const webAliases = { '/web': '/web/overview' };
export const resolveWebRoute = route => webAliases[route] || route;

export const requestSteps = [
  ['読者が記事を開く', 'ブラウザ', 'URLで、読みたい記事を指定します。', [0]],
  ['記事を要求する', 'ブラウザ → サーバー', 'ブラウザが「この記事をください」というHTTPリクエストを送ります。', [0, 1]],
  ['記事を探す', 'サーバー → データベース', 'バックエンドが、指定されたIDに対応する公開記事を問い合わせます。', [1, 2]],
  ['記事のデータが戻る', 'データベース → サーバー', 'タイトル・本文・著者IDなどの値が、バックエンドに返ります。', [1, 2]],
  ['HTMLを返す', 'サーバー → ブラウザ', 'この例では、バックエンドが記事データをテンプレートに入れてHTMLをつくります。', [0, 1]],
  ['画面を表示する', 'ブラウザ', 'ブラウザがHTMLからDOMを組み立て、CSSを適用して画面に描きます。', [0]],
];

export const webSources = {
  url: ['MDN：URLの各部分と役割', 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Web_mechanics/What_is_a_URL'],
  http: ['MDN：HTTPの要求と応答', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview'],
  tls: ['MDN：TLSによる通信の保護', 'https://developer.mozilla.org/en-US/docs/Web/Security/Defenses/Transport_Layer_Security'],
  http3: ['IETF：HTTP/3とQUIC（RFC 9114）', 'https://www.rfc-editor.org/rfc/rfc9114.html'],
  php: ['PHP：サーバーで動くスクリプト言語', 'https://www.php.net/intro'],
  laravel: ['Laravel：PHPでのルーティング', 'https://laravel.com/docs/routing'],
  django: ['Django：Pythonのウェブフレームワーク', 'https://www.djangoproject.com/start/'],
  rails: ['Ruby on Rails：基本の構成', 'https://guides.rubyonrails.org/getting_started.html'],
  routing: ['Express：メソッドとパスによるルーティング', 'https://expressjs.com/en/guide/routing/'],
  proxy: ['Nginx：リバースプロキシ', 'https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/'],
  transitions: ['MDN：CSSトランジション', 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Transitions/Using'],
  canvas: ['MDN：Canvasによる描画', 'https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API'],
  svg: ['MDN：SVG', 'https://developer.mozilla.org/en-US/docs/Web/SVG'],
  webgl: ['MDN：WebGL', 'https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API'],
  webgpu: ['MDN：WebGPU', 'https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API'],
  three: ['Three.js：シーン、カメラ、レンダラー', 'https://threejs.org/manual/#fundamentals'],
  d3: ['D3.js：データと視覚表現を結びつける', 'https://d3js.org/what-is-d3'],
  gsap: ['GSAP：アニメーションの制御', 'https://gsap.com/docs/v3/GSAP/'],
  modules: ['MDN：JavaScriptのモジュール', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules'],
  web: ['MDN：ウェブの仕組み', 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_the_web_works'],
  server: ['MDN：サーバー側で行う処理', 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/First_steps/Introduction'],
  html: ['MDN：HTML', 'https://developer.mozilla.org/en-US/docs/Web/HTML'],
  css: ['MDN：CSS', 'https://developer.mozilla.org/en-US/docs/Web/CSS'],
  dom: ['MDN：DOM', 'https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model'],
  jsHistory: ['Wirfs-Brock・Eich：JavaScriptの最初の20年（開発者らによる歴史・PDF）', 'https://wirfs-brock.com/allen/jshopl.pdf'],
  scripting: ['MDN：JavaScriptとは何か、どのように実行されるか', 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/What_is_JavaScript'],
  events: ['MDN：イベント', 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Events'],
  react: ['React：UIとコンポーネント', 'https://react.dev/learn'],
  state: ['React：インタラクションと状態', 'https://react.dev/learn/adding-interactivity'],
  vue: ['Vue：基本的な考え方', 'https://vuejs.org/guide/introduction.html'],
  svelte: ['Svelte：公式ドキュメント', 'https://svelte.dev/docs/svelte/overview'],
  angular: ['Angular：フレームワークの全体像', 'https://angular.dev/overview'],
  next: ['Next.js：公式ドキュメント', 'https://nextjs.org/docs'],
  nuxt: ['Nuxt：Vueと組み合わせたサイト構築', 'https://nuxt.com/docs/4.x/guide/concepts/vuejs-development'],
  node: ['Node.js：JavaScriptの実行環境', 'https://nodejs.org/en/learn/getting-started/introduction-to-nodejs'],
  typescript: ['TypeScript：JavaScriptとの関係', 'https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html'],
  relational: ['PostgreSQL：リレーショナルデータベースの基本', 'https://www.postgresql.org/docs/current/tutorial-concepts.html'],
  keys: ['PostgreSQL：主キー・外部キーと制約', 'https://www.postgresql.org/docs/current/ddl-constraints.html'],
  joins: ['PostgreSQL：テーブルの結合', 'https://www.postgresql.org/docs/current/tutorial-join.html'],
  editor: ['WordPress：記事を編集するブロックエディター', 'https://wordpress.org/documentation/article/wordpress-block-editor/'],
  rest: ['WordPress：REST API', 'https://developer.wordpress.org/rest-api/'],
  requirements: ['WordPress：実行環境とデータベース', 'https://wordpress.org/about/requirements/'],
  templates: ['WordPress：テンプレートの役割', 'https://developer.wordpress.org/themes/classic-themes/basics/template-files/'],
  posts: ['WordPress：記事のデータと公開状態', 'https://developer.wordpress.org/rest-api/reference/posts/'],
  fetch: ['MDN：JavaScriptからデータを取得する', 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch'],
  cookies: ['MDN：Cookie', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies'],
};
